# linkdin Web Scribing

In [111]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

print("Libraries installed successfully")

Libraries installed successfully

In [112]:
import requests

url = "https://www.linkedin.com/jobs/search/?keywords=ai%20and%20data&location=India"

response = requests.get(url)

print(response.status_code)
print(response.text[:500])

200
<!DOCTYPE html>
















































    <html lang="en">
      <head>
        <meta name="pageKey" content="d_jobs_guest_search">

    <meta name="robots" content="max-image-preview:large, noarchive">
    <meta name="bingbot" content="max-image-preview:large, archive">

<!---->          <met

In [113]:
headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.text[:500])

200
<!DOCTYPE html>
















































    <html lang="en">
      <head>
        <meta name="pageKey" content="d_jobs_guest_search">

    <meta name="robots" content="max-image-preview:large, noarchive">
    <meta name="bingbot" content="max-image-preview:large, archive">

<!---->          <met

In [114]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

print(soup.title)

<title>1,000+ Ai And Data jobs in India</title>

In [115]:
links = soup.find_all("a")

print("Total links:", len(links))

Total links: 147

In [116]:
for link in links[:10]:
    print(link.get_text(strip=True))

Skip to main content
LinkedIn
Join now
Sign in

Easy Apply
Under 10 applicants
Learn more
Sign in to create job alert
Lead - Data & AI

In [117]:
for tag in soup.find_all(["h1", "h2", "h3"])[:20]:
    print(tag.name, "→", tag.get_text(" ", strip=True))

h1 → 1,000+ Ai And Data Jobs in India
h3 → Lead - Data & AI
h3 → AI Data Engineer [T500-28265]
h3 → AI / ML Engineer
h3 → Data Platform Engineer
h3 → AI Engineer
h3 → Data Scientist-Artificial Intelligence
h3 → AI Engineer — Digital Transformation
h3 → AI/ML Data Science / Gen AI / MLOps
h3 → India: AI Analyst
h3 → DE-Python-AI-GDS
h3 → Predictive Analytics Data Scientist-AI Labs
h3 → Data Scientist
h3 → Head - Data & AI
h3 → Tech Lead - AI and Analytics Solutions
h3 → AI Architect
h3 → Data Scientist
h3 → Junior AI Specialist
h3 → Data Architect I - AI ML Architect
h3 → GEN AI Developer

In [118]:
job_titles = soup.find_all("h3")

print("Total job titles:", len(job_titles))

for i, job in enumerate(job_titles, start=1):
    print(i, "→", job.get_text(strip=True))

Total job titles: 60
1 → Lead - Data & AI
2 → AI Data Engineer [T500-28265]
3 → AI / ML Engineer
4 → Data Platform Engineer
5 → AI Engineer
6 → Data Scientist-Artificial Intelligence
7 → AI Engineer — Digital Transformation
8 → AI/ML Data Science / Gen AI / MLOps
9 → India: AI Analyst
10 → DE-Python-AI-GDS
11 → Predictive Analytics Data Scientist-AI Labs
12 → Data Scientist
13 → Head - Data & AI
14 → Tech Lead - AI and Analytics Solutions
15 → AI Architect
16 → Data Scientist
17 → Junior AI Specialist
18 → Data Architect I - AI ML Architect
19 → GEN AI Developer
20 → Data Scientist
21 → Agentic Solutions-AI and Data Science Engineer II
22 → GEN AI
23 → AI Engineer (Data &amp; AI Practice)
24 → Data Scientist (Microsoft 365 Copilot / AI)
25 → Data Scientist – LLM & Applied AI
26 → Data Scientist
27 → AI/ML Engineer
28 → AI/ML Lead
29 → Machine Learning  Engineer Mid Level
30 → AI / ML Engineer
31 → Artificial Intelligence Manager
32 → Gen AI |
ML- Data Scientist
33 → Data Engineer
34 → ML-Ops
35 → Senior Data Scientist
36 → Junior Data Scientist
37 → CT-NITRO-Experimental AI Engineer
38 → AI Engineer
39 → Digital Transformation & AI Specialist - Ahmedabad, India
40 → Data Scientist
41 → AI Engineer / Machine Learning Engineer
42 → Data Scientist
43 → Data Scientist - Marketing & Sales
44 → Gen AI-AI and Data Science Engineer III
45 → Artificial Intelligence Engineer
46 → Artificial Intelligence Engineer
47 → AI/LLM Data Intelligence Engineer
48 → Data Scientist
49 → Gen AI |
ML- Data Scientist
50 → Data Scientist
51 → ML Engineer I
52 → AI & Data Engineer (AIDE)
53 → AI Technical Lead
54 → AI/ML Engineer
55 → Artificial Intelligence Data Engineer
56 → AI Engineer
57 → Straviso - Data Scientist - Artificial Intelligence/Machine Learning
58 → Machine Learning
59 → Data Scientist (R-19646)
60 → Data Architect - Gen AI

In [119]:
job_title_list = []

for job in job_titles:
    title = job.get_text(strip=True)
    job_title_list.append(title)

print(job_title_list)

['Lead - Data & AI', 'AI Data Engineer [T500-28265]', 'AI / ML Engineer', 'Data Platform Engineer', 'AI Engineer', 'Data Scientist-Artificial Intelligence', 'AI Engineer — Digital Transformation', 'AI/ML Data Science / Gen AI / MLOps', 'India: AI Analyst', 'DE-Python-AI-GDS', 'Predictive Analytics Data Scientist-AI Labs', 'Data Scientist', 'Head - Data & AI', 'Tech Lead - AI and Analytics Solutions', 'AI Architect', 'Data Scientist', 'Junior AI Specialist', 'Data Architect I - AI ML Architect', 'GEN AI Developer', 'Data Scientist', 'Agentic Solutions-AI and Data Science Engineer II', 'GEN AI', 'AI Engineer (Data &amp; AI Practice)', 'Data Scientist (Microsoft 365 Copilot / AI)', 'Data Scientist – LLM & Applied AI', 'Data Scientist', 'AI/ML Engineer', 'AI/ML Lead', 'Machine Learning  Engineer Mid Level', 'AI / ML Engineer', 'Artificial Intelligence Manager', 'Gen AI |\nML- Data Scientist', 'Data Engineer', 'ML-Ops', 'Senior Data Scientist', 'Junior Data Scientist', 'CT-NITRO-Experimental AI Engineer', 'AI Engineer', 'Digital Transformation & AI Specialist - Ahmedabad, India', 'Data Scientist', 'AI Engineer / Machine Learning Engineer', 'Data Scientist', 'Data Scientist - Marketing & Sales', 'Gen AI-AI and Data Science Engineer III', 'Artificial Intelligence Engineer', 'Artificial Intelligence Engineer', 'AI/LLM Data Intelligence Engineer', 'Data Scientist', 'Gen AI |\nML- Data Scientist', 'Data Scientist', 'ML Engineer I', 'AI & Data Engineer (AIDE)', 'AI Technical Lead', 'AI/ML Engineer', 'Artificial Intelligence Data Engineer', 'AI Engineer', 'Straviso - Data Scientist - Artificial Intelligence/Machine Learning', 'Machine Learning', 'Data Scientist (R-19646)', 'Data Architect - Gen AI']

In [120]:
print("Number of jobs:", len(job_title_list))

Number of jobs: 60

In [121]:
first_job = soup.find("h3")

print(first_job.parent.prettify()[:3000])

<div class="base-search-card__info">
 <h3 class="base-search-card__title">
  Lead - Data &amp; AI
 </h3>
 <h4 class="base-search-card__subtitle">
  <a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://in.linkedin.com/company/adaninaturalresources?trk=public_jobs_jserp-result_job-search-card-subtitle">
   Adani Natural Resources
  </a>
 </h4>
 <!-- -->
 <div class="base-search-card__metadata">
  <span class="job-search-card__location">
   Ahmedabad, Gujarat, India
  </span>
  <!-- -->
  <time class="job-search-card__listdate" datetime="2026-08-13">
   1 week ago
  </time>
  <!-- -->
 </div>
</div>

In [122]:
job_info = soup.find("div", class_="base-search-card__info")

title = job_info.find("h3").get_text(strip=True)

company = job_info.find("h4").get_text(strip=True)

location = job_info.find(
    "span",
    class_="job-search-card__location"
).get_text(strip=True)

print("Title:", title)
print("Company:", company)
print("Location:", location)

Title: Lead - Data & AI
Company: Adani Natural Resources
Location: Ahmedabad, Gujarat, India

In [123]:
company_link = job_info.find("h4").find("a")

print(company_link.get("href"))

https://in.linkedin.com/company/adaninaturalresources?trk=public_jobs_jserp-result_job-search-card-subtitle

In [124]:
job_card = job_info.parent

print(job_card.prettify()[:5000])

<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4427195843" data-impression-id="jobs-search-desktop-0" data-reference-id="atayXtxeJh9td1JiQtu/DA==" data-row="1" data-tracking-id="YB+ciEh0pQSAOWp+wOGs6A==">
 <a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&amp;pageNum=0&amp;refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&amp;trackingId=YB%2BciEh0pQSAOWp%2BwOGs6A%3D%3D">
  <span class="sr-only">
   Lead - Data &amp; AI
  </span>
 </a>
 <div class="search-entity-media">
  <img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/D4D0BAQHtu5H3xVXm_w/company-logo_100_100/B4DZhQ6lI4GkAQ-/0/1753704191340/adaninaturalresources_logo?e=2147483647&amp;v=beta&amp;t=DY2-Msp6tCIm1FoL1neoU3OnywCzR55NOHbcMHpORxE" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
 </div>
 <div class="base-search-card__info">
  <h3 class="base-search-card__title">
   Lead - Data &amp; AI
  </h3>
  <h4 class="base-search-card__subtitle">
   <a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://in.linkedin.com/company/adaninaturalresources?trk=public_jobs_jserp-result_job-search-card-subtitle">
    Adani Natural Resources
   </a>
  </h4>
  <!-- -->
  <div class="base-search-card__metadata">
   <span class="job-search-card__location">
    Ahmedabad, Gujarat, India
   </span>
   <!-- -->
   <time class="job-search-card__listdate" datetime="2026-08-13">
    1 week ago
   </time>
   <!-- -->
  </div>
 </div>
 <!-- -->
</div>

In [125]:
job_links = soup.find_all(
    "a",
    href=lambda x: x and "/jobs/view/" in x
)

print("Job links:", len(job_links))

for link in job_links[:5]:
    print(link.get("href"))

Job links: 60
https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=YB%2BciEh0pQSAOWp%2BwOGs6A%3D%3D
https://in.linkedin.com/jobs/view/ai-data-engineer-t500-28265-at-comply-4450235303?position=2&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=Yw8T0rUiMVgXqkBdjPPOvw%3D%3D
https://in.linkedin.com/jobs/view/ai-ml-engineer-at-accenture-in-india-4448497520?position=3&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=OZwvWPH5oj7ZAjqSkUnsDw%3D%3D
https://in.linkedin.com/jobs/view/data-platform-engineer-at-accenture-in-india-4448338922?position=4&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=o6YApkeW%2FAHBPbzHXNyGog%3D%3D
https://in.linkedin.com/jobs/view/ai-engineer-at-shamrock-ai-4430825102?position=5&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=KYZXqkM4VSL2vZLcf5EjAQ%3D%3D

In [126]:
job_cards = soup.find_all("div", class_="base-search-card")

print("Total job cards:", len(job_cards))

Total job cards: 60

In [127]:
card = job_cards[0]

title = card.find(
    "h3",
    class_="base-search-card__title"
).get_text(strip=True)

company = card.find(
    "h4",
    class_="base-search-card__subtitle"
).get_text(strip=True)

location = card.find(
    "span",
    class_="job-search-card__location"
).get_text(strip=True)

print("Title:", title)
print("Company:", company)
print("Location:", location)

Title: Lead - Data & AI
Company: Adani Natural Resources
Location: Ahmedabad, Gujarat, India

In [128]:
job_link = card.find(
    "a",
    href=lambda x: x and "/jobs/view/" in x
)

print(job_link.get("href"))

https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=YB%2BciEh0pQSAOWp%2BwOGs6A%3D%3D

In [129]:
date = card.find("time")

print(date.get_text(strip=True))
print(date.get("datetime"))

1 week ago
2026-08-13

In [130]:
jobs = []

for card in job_cards:

    # Job title
    title = card.find(
        "h3",
        class_="base-search-card__title"
    ).get_text(strip=True)

    # Company
    company = card.find(
        "h4",
        class_="base-search-card__subtitle"
    ).get_text(strip=True)

    # Location
    location = card.find(
        "span",
        class_="job-search-card__location"
    ).get_text(strip=True)

    # Job URL
    job_link = card.find(
        "a",
        href=lambda x: x and "/jobs/view/" in x
    )

    job_url = job_link.get("href") if job_link else None

    # Posted date
    date_tag = card.find("time")

    posted_text = date_tag.get_text(strip=True) if date_tag else None
    posted_date = date_tag.get("datetime") if date_tag else None

    # Store the job
    jobs.append({
        "title": title,
        "company": company,
        "location": location,
        "job_url": job_url,
        "posted_text": posted_text,
        "posted_date": posted_date
    })

print("Total jobs:", len(jobs))

Total jobs: 60

In [131]:
print(jobs[0])

{'title': 'Lead - Data & AI', 'company': 'Adani Natural Resources', 'location': 'Ahmedabad, Gujarat, India', 'job_url': 'https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=YB%2BciEh0pQSAOWp%2BwOGs6A%3D%3D', 'posted_text': '1 week ago', 'posted_date': '2026-08-13'}

In [132]:
for job in jobs[:5]:
    print(job)
    print("-" * 50)

{'title': 'Lead - Data & AI', 'company': 'Adani Natural Resources', 'location': 'Ahmedabad, Gujarat, India', 'job_url': 'https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=YB%2BciEh0pQSAOWp%2BwOGs6A%3D%3D', 'posted_text': '1 week ago', 'posted_date': '2026-08-13'}
--------------------------------------------------
{'title': 'AI Data Engineer [T500-28265]', 'company': 'Comply', 'location': 'Kochi, Kerala, India', 'job_url': 'https://in.linkedin.com/jobs/view/ai-data-engineer-t500-28265-at-comply-4450235303?position=2&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=Yw8T0rUiMVgXqkBdjPPOvw%3D%3D', 'posted_text': '2 weeks ago', 'posted_date': '2026-08-06'}
--------------------------------------------------
{'title': 'AI / ML Engineer', 'company': 'Accenture in India', 'location': 'Coimbatore, Tamil Nadu, India', 'job_url': 'https://in.linkedin.com/jobs/view/ai-ml-engineer-at-accenture-in-india-4448497520?position=3&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=OZwvWPH5oj7ZAjqSkUnsDw%3D%3D', 'posted_text': '2 weeks ago', 'posted_date': '2026-08-07'}
--------------------------------------------------
{'title': 'Data Platform Engineer', 'company': 'Accenture in India', 'location': 'Bhubaneswar, Odisha, India', 'job_url': 'https://in.linkedin.com/jobs/view/data-platform-engineer-at-accenture-in-india-4448338922?position=4&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=o6YApkeW%2FAHBPbzHXNyGog%3D%3D', 'posted_text': '21 hours ago', 'posted_date': '2026-08-25'}
--------------------------------------------------
{'title': 'AI Engineer', 'company': 'Shamrock AI', 'location': 'Shillong, Meghalaya, India', 'job_url': 'https://in.linkedin.com/jobs/view/ai-engineer-at-shamrock-ai-4430825102?position=5&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=KYZXqkM4VSL2vZLcf5EjAQ%3D%3D', 'posted_text': '2 months ago', 'posted_date': '2026-06-22'}
--------------------------------------------------

In [133]:
url = "https://www.linkedin.com/jobs/search/?keywords=ai%20and%20data&location=India&start=25"

response = requests.get(url, headers=headers)

print("Status:", response.status_code)

soup2 = BeautifulSoup(response.text, "html.parser")

job_cards2 = soup2.find_all(
    "div",
    class_="base-search-card"
)

print("Jobs found:", len(job_cards2))

Status: 200
Jobs found: 60

In [134]:
print("Page 1:", job_cards[0].find(
    "h3",
    class_="base-search-card__title"
).get_text(strip=True))

print("Page 2:", job_cards2[0].find(
    "h3",
    class_="base-search-card__title"
).get_text(strip=True))

Page 1: Lead - Data & AI
Page 2: Data Scientist-Artificial Intelligence

In [135]:
print(response.url)

https://www.linkedin.com/jobs/search/?keywords=ai+and+data&location=India&start=0

In [136]:
print(soup2.title.get_text(strip=True))

Ai And Data Jobs in India (11,000+ Open Roles) | LinkedIn

In [137]:
for card in job_cards2[:5]:

    link = card.find(
        "a",
        href=lambda x: x and "/jobs/view/" in x
    )

    print(link.get("href") if link else "No URL")

https://in.linkedin.com/jobs/view/data-scientist-artificial-intelligence-at-ibm-4446241710?position=1&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=biJsfv35j113Xei3ApX8Bg%3D%3D
https://in.linkedin.com/jobs/view/senior-data-scientist-i-at-metlife-4455731862?position=2&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=%2BNSIzt%2Fm6Oj8Q9gNK9olUA%3D%3D
https://in.linkedin.com/jobs/view/senior-data-scientist-at-sourcingxpress-4384572454?position=3&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=jpzKY1vEVSovWSTMEE38sw%3D%3D
https://in.linkedin.com/jobs/view/sr-advanced-data-scientist-at-honeywell-technologies-4445700716?position=4&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=pDFOdYmYS%2BEExwaKERxlMw%3D%3D
https://in.linkedin.com/jobs/view/senior-data-scientist-i-at-metlife-4446306265?position=5&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=aR5FEJyxdbaQOgcxxa4PAQ%3D%3D

In [138]:
page1_urls = []

for card in job_cards[:5]:

    link = card.find(
        "a",
        href=lambda x: x and "/jobs/view/" in x
    )

    if link:
        page1_urls.append(link.get("href"))


page2_urls = []

for card in job_cards2[:5]:

    link = card.find(
        "a",
        href=lambda x: x and "/jobs/view/" in x
    )

    if link:
        page2_urls.append(link.get("href"))


print("Page 1 URLs:")
print(page1_urls)

print("\nPage 2 URLs:")
print(page2_urls)

print("\nSame results:", page1_urls == page2_urls)

Page 1 URLs:
['https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=YB%2BciEh0pQSAOWp%2BwOGs6A%3D%3D', 'https://in.linkedin.com/jobs/view/ai-data-engineer-t500-28265-at-comply-4450235303?position=2&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=Yw8T0rUiMVgXqkBdjPPOvw%3D%3D', 'https://in.linkedin.com/jobs/view/ai-ml-engineer-at-accenture-in-india-4448497520?position=3&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=OZwvWPH5oj7ZAjqSkUnsDw%3D%3D', 'https://in.linkedin.com/jobs/view/data-platform-engineer-at-accenture-in-india-4448338922?position=4&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=o6YApkeW%2FAHBPbzHXNyGog%3D%3D', 'https://in.linkedin.com/jobs/view/ai-engineer-at-shamrock-ai-4430825102?position=5&pageNum=0&refId=atayXtxeJh9td1JiQtu%2FDA%3D%3D&trackingId=KYZXqkM4VSL2vZLcf5EjAQ%3D%3D']

Page 2 URLs:
['https://in.linkedin.com/jobs/view/data-scientist-artificial-intelligence-at-ibm-4446241710?position=1&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=biJsfv35j113Xei3ApX8Bg%3D%3D', 'https://in.linkedin.com/jobs/view/senior-data-scientist-i-at-metlife-4455731862?position=2&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=%2BNSIzt%2Fm6Oj8Q9gNK9olUA%3D%3D', 'https://in.linkedin.com/jobs/view/senior-data-scientist-at-sourcingxpress-4384572454?position=3&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=jpzKY1vEVSovWSTMEE38sw%3D%3D', 'https://in.linkedin.com/jobs/view/sr-advanced-data-scientist-at-honeywell-technologies-4445700716?position=4&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=pDFOdYmYS%2BEExwaKERxlMw%3D%3D', 'https://in.linkedin.com/jobs/view/senior-data-scientist-i-at-metlife-4446306265?position=5&pageNum=0&refId=P2dAuHs%2FV7BhiRx576okIA%3D%3D&trackingId=aR5FEJyxdbaQOgcxxa4PAQ%3D%3D']

Same results: False

In [139]:
def scrape_page(start):

    url = f"https://www.linkedin.com/jobs/search/?keywords=ai%20and%20data&location=India&start={start}"

    response = requests.get(url, headers=headers)

    print("Start:", start, "Status:", response.status_code)

    soup = BeautifulSoup(response.text, "html.parser")

    job_cards = soup.find_all(
        "div",
        class_="base-search-card"
    )

    page_jobs = []

    for card in job_cards:

        title_tag = card.find(
            "h3",
            class_="base-search-card__title"
        )

        company_tag = card.find(
            "h4",
            class_="base-search-card__subtitle"
        )

        location_tag = card.find(
            "span",
            class_="job-search-card__location"
        )

        link_tag = card.find(
            "a",
            href=lambda x: x and "/jobs/view/" in x
        )

        date_tag = card.find("time")

        page_jobs.append({
            "title": title_tag.get_text(strip=True) if title_tag else None,
            "company": company_tag.get_text(strip=True) if company_tag else None,
            "location": location_tag.get_text(strip=True) if location_tag else None,
            "job_url": link_tag.get("href") if link_tag else None,
            "posted_text": date_tag.get_text(strip=True) if date_tag else None,
            "posted_date": date_tag.get("datetime") if date_tag else None
        })

    return page_jobs

In [140]:
page1 = scrape_page(0)

print("Jobs:", len(page1))
print(page1[0])

Start: 0 Status: 200
Jobs: 60
{'title': 'Lead - Data & AI', 'company': 'Adani Natural Resources', 'location': 'Ahmedabad, Gujarat, India', 'job_url': 'https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=H4e7XdShn7HSewhDouA4gg%3D%3D&trackingId=d9fF5jMd6NdS6EvQucsGUA%3D%3D', 'posted_text': '1 week ago', 'posted_date': '2026-08-13'}

In [141]:
page2 = scrape_page(25)

print("Jobs:", len(page2))
print(page2[0])

Start: 25 Status: 200
Jobs: 60
{'title': 'Lead - Data & AI', 'company': 'Adani Natural Resources', 'location': 'Ahmedabad, Gujarat, India', 'job_url': 'https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=UFyWjdztFMzOrcihDtyNpQ%3D%3D&trackingId=LOXjltFocoigT1sIoOlmfA%3D%3D', 'posted_text': '1 week ago', 'posted_date': '2026-08-13'}

In [142]:
print(page1[0]["job_url"])
print(page2[0]["job_url"])

print("Different:", page1[0]["job_url"] != page2[0]["job_url"])

https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=H4e7XdShn7HSewhDouA4gg%3D%3D&trackingId=d9fF5jMd6NdS6EvQucsGUA%3D%3D
https://in.linkedin.com/jobs/view/lead-data-ai-at-adani-natural-resources-4427195843?position=1&pageNum=0&refId=UFyWjdztFMzOrcihDtyNpQ%3D%3D&trackingId=LOXjltFocoigT1sIoOlmfA%3D%3D
Different: True

In [143]:
all_jobs = []

for start in range(0, 125, 25):

    page_jobs = scrape_page(start)

    all_jobs.extend(page_jobs)

    print("Total collected:", len(all_jobs))

Start: 0 Status: 200
Total collected: 60
Start: 25 Status: 200
Total collected: 120
Start: 50 Status: 200
Total collected: 180
Start: 75 Status: 200
Total collected: 240
Start: 100 Status: 200
Total collected: 300

In [144]:
jobs = [job for job in unique_jobs.values()]

print("Total scraped:", len(all_jobs))
print("Unique jobs:", len(jobs))

Total scraped: 300
Unique jobs: 240

In [145]:
df = pd.DataFrame(jobs)

print(df.shape)

df.head()

(240, 6)

,title,company,location,job_url,posted_text,posted_date
0,Data Scientist-Artificial Intelligence,IBM,"Kochi, Kerala, India",https://in.linkedin.com/jobs/view/data-scienti...,17 hours ago,2026-08-25
1,Senior Data Scientist - I,MetLife,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/senior-data-...,20 hours ago,2026-08-25
2,Senior Data Scientist,SourcingXPress,"Gurgaon, Haryana, India",https://in.linkedin.com/jobs/view/senior-data-...,5 months ago,2026-03-16
3,Sr Advanced Data Scientist,Honeywell Technologies,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/sr-advanced-...,1 week ago,2026-08-18
4,Senior Data Scientist I,MetLife,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/senior-data-...,3 weeks ago,2026-08-03

In [146]:
target = 2000

all_jobs = []
seen_urls = set()

for start in range(0, 5000, 25):

    page_jobs = scrape_page(start)

    if not page_jobs:
        print("No jobs found. Stopping.")
        break

    for job in page_jobs:

        job_url = job["job_url"]

        if job_url and job_url not in seen_urls:
            seen_urls.add(job_url)
            all_jobs.append(job)

    print(
        "Start:", start,
        "| New jobs:", len(page_jobs),
        "| Unique jobs:", len(all_jobs)
    )

    if len(all_jobs) >= target:
        break

Start: 0 Status: 200
Start: 0 | New jobs: 60 | Unique jobs: 60
Start: 25 Status: 429
No jobs found. Stopping.

In [147]:
df = pd.DataFrame(all_jobs)

print(df.shape)

df.to_csv("linkedin_jobs_240.csv", index=False)

print("Saved successfully!")

(60, 6)
Saved successfully!

In [148]:
print(df.columns)

Index(['title', 'company', 'location', 'job_url', 'posted_text',
       'posted_date'],
      dtype='str')

In [149]:
df.head()

,title,company,location,job_url,posted_text,posted_date
0,Data Scientist-Artificial Intelligence,IBM,"Kochi, Kerala, India",https://in.linkedin.com/jobs/view/data-scienti...,18 hours ago,2026-08-25
1,Senior Data Scientist - I,MetLife,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/senior-data-...,22 hours ago,2026-08-25
2,Senior Data Scientist,SourcingXPress,"Gurgaon, Haryana, India",https://in.linkedin.com/jobs/view/senior-data-...,5 months ago,2026-03-16
3,Sr Advanced Data Scientist,Honeywell Technologies,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/sr-advanced-...,1 week ago,2026-08-18
4,Senior Data Scientist I,MetLife,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/senior-data-...,3 weeks ago,2026-08-03

In [150]:
import time
import requests
from bs4 import BeautifulSoup

In [151]:
def scrape_page(start):

    url = (
        "https://www.linkedin.com/jobs/search/"
        "?keywords=ai%20and%20data"
        "&location=India"
        f"&start={start}"
    )

    response = requests.get(
        url,
        headers=headers,
        timeout=20
    )

    print("Start:", start, "Status:", response.status_code)

    if response.status_code == 429:
        print("Rate limit reached. Stopping requests.")
        return None

    if response.status_code != 200:
        print("Request failed.")
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    job_cards = soup.find_all(
        "div",
        class_="base-search-card"
    )

    page_jobs = []

    for card in job_cards:

        title_tag = card.find(
            "h3",
            class_="base-search-card__title"
        )

        company_tag = card.find(
            "h4",
            class_="base-search-card__subtitle"
        )

        location_tag = card.find(
            "span",
            class_="job-search-card__location"
        )

        link_tag = card.find(
            "a",
            href=lambda x: x and "/jobs/view/" in x
        )

        date_tag = card.find("time")

        page_jobs.append({
            "title": title_tag.get_text(strip=True) if title_tag else None,
            "company": company_tag.get_text(strip=True) if company_tag else None,
            "location": location_tag.get_text(strip=True) if location_tag else None,
            "job_url": link_tag.get("href") if link_tag else None,
            "posted_text": date_tag.get_text(strip=True) if date_tag else None,
            "posted_date": date_tag.get("datetime") if date_tag else None
        })

    return page_jobs

In [152]:
time.sleep(60)

test_jobs = scrape_page(125)

print("Jobs returned:", len(test_jobs) if test_jobs else 0)

Start: 125 Status: 200
Jobs returned: 60

In [153]:
for job in test_jobs:
    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 120

In [154]:
time.sleep(60)

page_jobs = scrape_page(150)

if page_jobs:
    for job in page_jobs:
        job_url = job["job_url"]

        if job_url and job_url not in seen_urls:
            seen_urls.add(job_url)
            all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Start: 150 Status: 200
Total unique jobs: 180

In [155]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 180 jobs

In [156]:
import time

time.sleep(60)

page_jobs = scrape_page(175)

print("Jobs returned:", len(page_jobs) if page_jobs else 0)

Start: 175 Status: 200
Jobs returned: 60

In [157]:
for job in page_jobs:

    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 240

In [158]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 240 jobs

In [159]:
import time

time.sleep(60)

page_jobs = scrape_page(175)

print("Jobs returned:", len(page_jobs) if page_jobs else 0)

Start: 175 Status: 200
Jobs returned: 60

In [160]:
for job in page_jobs:

    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 300

In [161]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 300 jobs

In [162]:
import time

time.sleep(60)

page_jobs = scrape_page(200)

print("Jobs returned:", len(page_jobs) if page_jobs else 0)

Start: 200 Status: 200
Jobs returned: 60

In [163]:
for job in page_jobs:

    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 360

In [164]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 360 jobs

In [165]:
import time

time.sleep(60)

page_jobs = scrape_page(225)

print("Jobs returned:", len(page_jobs) if page_jobs else 0)

Start: 225 Status: 200
Jobs returned: 60

In [166]:
for job in page_jobs:

    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 420

In [167]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 420 jobs

In [168]:
import time

time.sleep(60)

page_jobs = scrape_page(600)

print("Jobs returned:", len(page_jobs) if page_jobs else 0)

Start: 600 Status: 200
Jobs returned: 60

In [169]:
for job in page_jobs:

    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 480

In [170]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 480 jobs

In [171]:
import time

time.sleep(60)

page_jobs = scrape_page(800)

print("Jobs returned:", len(page_jobs) if page_jobs else 0)

Start: 800 Status: 200
Jobs returned: 60

In [172]:
for job in page_jobs:

    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 540

In [173]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 540 jobs

In [174]:
import time

time.sleep(60)

page_jobs = scrape_page(1000)

print("Jobs returned:", len(page_jobs) if page_jobs else 0)

Start: 1000 Status: 200
Jobs returned: 60

In [175]:
for job in page_jobs:

    job_url = job["job_url"]

    if job_url and job_url not in seen_urls:
        seen_urls.add(job_url)
        all_jobs.append(job)

print("Total unique jobs:", len(all_jobs))

Total unique jobs: 600

In [176]:
df = pd.DataFrame(all_jobs)

df.to_csv("linkedin_jobs_progress.csv", index=False)

print("Saved:", len(df), "jobs")

Saved: 600 jobs

In [177]:
job_url = df.loc[0, "job_url"]

print(job_url)

https://in.linkedin.com/jobs/view/data-scientist-artificial-intelligence-at-ibm-4446241710?position=1&pageNum=0&refId=x8S%2B68uVhJjbnbv4CmsPww%3D%3D&trackingId=SvOZkJNmAmrAO7HXXxVCQg%3D%3D

In [178]:
response = requests.get(
    job_url,
    headers=headers,
    timeout=20
)

print("Status:", response.status_code)
print(response.text[:500])

Status: 200
<!DOCTYPE html>

















    <html lang="en">
      <head>
        <meta name="pageKey" content="d_jobs_guest_details">

    <meta name="robots" content="max-image-preview:large, noarchive">
    <meta name="bingbot" content="max-image-preview:large, archive">

<!----><!---->        <meta name="locale" content="en_US">
<!---->        <meta id="config" data-app-version="2.0.3115" data-call-tree-id="AAZZ8jfNIn1/nMJYwC+4

In [179]:
job_soup = BeautifulSoup(
    response.text,
    "html.parser"
)

print(job_soup.title)

<title>IBM hiring Data Scientist-Artificial Intelligence in Kochi, Kerala, India | LinkedIn</title>

In [180]:
text = job_soup.get_text(" ", strip=True)

for keyword in ["Experience", "Salary", "Skills", "Full-time", "Contract"]:
    print(keyword, "→", keyword.lower() in text.lower())

Experience → True
Salary → False
Skills → True
Full-time → True
Contract → False

In [181]:
for tag in job_soup.find_all(string=lambda x: x and "experience" in x.lower()):
    print(tag.parent)

<script type="application/ld+json">
      {"@context":"http://schema.org","@type":"JobPosting","datePosted":"2026-08-25T17:14:58.000Z","description":"&lt;strong&gt;Introduction&lt;br&gt;&lt;br&gt;&lt;/strong&gt;A career in IBM Consulting is built on long-term client relationships and close collaboration worldwide. You’ll work with leading companies across industries, helping them shape their hybrid cloud and AI journeys. With support from our strategic partners, robust IBM technology, and Red Hat, you’ll have the tools to drive meaningful change and accelerate client impact. At IBM Consulting, curiosity fuels success. You’ll be encouraged to challenge the norm, explore new ideas, and create innovative solutions that deliver real results. Our culture of growth and empathy focuses on your long-term career development while valuing your unique skills and experiences.&lt;br&gt;&lt;br&gt;&lt;strong&gt;Your Role And Responsibilities&lt;br&gt;&lt;br&gt;&lt;/strong&gt;As a Data Scientist with expertise in Artificial Intelligence, you will skillfully combine data analysis and business acumen to tackle cognitive computing challenges. You will be responsible for architecting and delivering AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models. Your primary responsibilities will include:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt; Design AI Solutions: Architect and deliver AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models, and experience in tools like Github Copilot and Amazon Code Whisperer.&lt;/li&gt;&lt;li&gt; Develop Cognitive Solutions: Create comprehensive cognitive solutions that effectively process and analyze both structured and unstructured data, utilizing expertise in NLP, ML, and other specialized areas such as Image Processing, Video Processing, Voice Processing, or Watson technologies.&lt;/li&gt;&lt;li&gt; Implement AI Frameworks: Apply strong programming skills, with proficiency in Python and experience with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, to develop and deploy AI models.&lt;/li&gt;&lt;li&gt; Manage AI Project Lifecycle: Oversee the full AI project lifecycle, from research and prototyping to deployment in production environments, ensuring successful project delivery.&lt;/li&gt;&lt;li&gt; Collaborate with Stakeholders: Work with various stakeholders to identify business problems and leverage the power of artificial intelligence for cognitive computing, driving business value through AI-driven solutions.&lt;br&gt;&lt;br&gt;&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Preferred Education&lt;br&gt;&lt;br&gt;&lt;/strong&gt;Master's Degree&lt;br&gt;&lt;br&gt;&lt;strong&gt;Required Technical And Professional Expertise&lt;br&gt;&lt;br&gt;&lt;/strong&gt;&lt;ul&gt;&lt;li&gt; Advanced Analytics Techniques: Exposure to advanced analytics techniques for structured data, including data analysis and interpretation, to inform business decisions and tackle cognitive computing challenges.&lt;/li&gt;&lt;li&gt; AI Frameworks and Tools: Experience working with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, and tools like Github Copilot and Amazon Code Whisperer to develop and deploy AI models.&lt;/li&gt;&lt;li&gt; Programming Skills: Proficiency in Python programming language, with experience in applying programming skills to develop and deploy AI solutions.&lt;/li&gt;&lt;li&gt; NLP and ML Methods: Exposure to Natural Language Processing (NLP) and Machine Learning (ML) methods for unstructured content, including foundation models and large language models.&lt;/li&gt;&lt;li&gt; Cloud Platforms and Databases: Experience working with cloud platforms (e.g. Kubernetes, AWS, Azure, GCP) and related services, as well as relational and NoSQL databases (SQL, Postgres, DB2, MongoDB).&lt;br&gt;&lt;br&gt;&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Preferred Technical And Professional Experience&lt;br&gt;&lt;br&gt;&lt;/strong&gt;&lt;ul&gt;&lt;li&gt; Familiarity with Modern UI: Familiarity with modern UI frameworks such as Backbone.js, AngularJS, React.js, Ember.js, Bootstrap, and JQuery, with the ability to apply this knowledge in developing AI solutions.&lt;/li&gt;&lt;li&gt; Understanding of Libraries: Understanding in the usage of libraries such as SciKit Learn, Pandas, Matplotlib, etc., with the ability to apply this knowledge in developing AI solutions.&lt;/li&gt;&lt;li&gt; Operating Systems Knowledge: Experience working with various operating systems (Linux, Windows, iOS, Android), with the ability to apply this knowledge in developing and deploying AI solutions.&lt;/li&gt;&lt;/ul&gt;","employmentType":"FULL_TIME","hiringOrganization":{"@type":"Organization","name":"IBM","sameAs":"https://www.linkedin.com/company/ibm","logo":"https://media.licdn.com/dms/image/v2/D560BAQGiz5ecgpCtkA/company-logo_200_200/company-logo_200_200/0/1688684715866/ibm_logo?e=2147483647&amp;v=beta&amp;t=yWxQj1oew7nR92bDw8r80j2EiCwx29aNxLZktJYrsWw"},"identifier":{"@type":"PropertyValue","name":"IBM","value":"114150"},"image":"https://media.licdn.com/dms/image/v2/D560BAQGiz5ecgpCtkA/company-logo_100_100/company-logo_100_100/0/1688684715866/ibm_logo?e=2147483647&amp;v=beta&amp;t=HPSmWLOCvdPkWO1nRWwjjmCNpaCqww20rSJ4E54QtxQ","industry":"IT Services and IT Consulting","jobLocation":{"@type":"Place","address":{"@type":"PostalAddress","addressCountry":"IN","addressLocality":"Kochi","addressRegion":null,"streetAddress":null},"latitude":9.957617,"longitude":76.25115},"skills":"","title":"Data Scientist-Artificial Intelligence","validThrough":"2026-10-02T20:27:31.000Z","educationRequirements":{"@type":"EducationalOccupationalCredential","credentialCategory":"bachelor degree"}}
    </script>
<div class="show-more-less-html__markup show-more-less-html__markup--clamp-after-5 relative overflow-hidden">
<strong>Introduction<br/><br/></strong>A career in IBM Consulting is built on long-term client relationships and close collaboration worldwide. You’ll work with leading companies across industries, helping them shape their hybrid cloud and AI journeys. With support from our strategic partners, robust IBM technology, and Red Hat, you’ll have the tools to drive meaningful change and accelerate client impact. At IBM Consulting, curiosity fuels success. You’ll be encouraged to challenge the norm, explore new ideas, and create innovative solutions that deliver real results. Our culture of growth and empathy focuses on your long-term career development while valuing your unique skills and experiences.<br/><br/><strong>Your Role And Responsibilities<br/><br/></strong>As a Data Scientist with expertise in Artificial Intelligence, you will skillfully combine data analysis and business acumen to tackle cognitive computing challenges. You will be responsible for architecting and delivering AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models. Your primary responsibilities will include:<br/><br/><ul><li> Design AI Solutions: Architect and deliver AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models, and experience in tools like Github Copilot and Amazon Code Whisperer.</li><li> Develop Cognitive Solutions: Create comprehensive cognitive solutions that effectively process and analyze both structured and unstructured data, utilizing expertise in NLP, ML, and other specialized areas such as Image Processing, Video Processing, Voice Processing, or Watson technologies.</li><li> Implement AI Frameworks: Apply strong programming skills, with proficiency in Python and experience with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, to develop and deploy AI models.</li><li> Manage AI Project Lifecycle: Oversee the full AI project lifecycle, from research and prototyping to deployment in production environments, ensuring successful project delivery.</li><li> Collaborate with Stakeholders: Work with various stakeholders to identify business problems and leverage the power of artificial intelligence for cognitive computing, driving business value through AI-driven solutions.<br/><br/></li></ul><strong>Preferred Education<br/><br/></strong>Master's Degree<br/><br/><strong>Required Technical And Professional Expertise<br/><br/></strong><ul><li> Advanced Analytics Techniques: Exposure to advanced analytics techniques for structured data, including data analysis and interpretation, to inform business decisions and tackle cognitive computing challenges.</li><li> AI Frameworks and Tools: Experience working with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, and tools like Github Copilot and Amazon Code Whisperer to develop and deploy AI models.</li><li> Programming Skills: Proficiency in Python programming language, with experience in applying programming skills to develop and deploy AI solutions.</li><li> NLP and ML Methods: Exposure to Natural Language Processing (NLP) and Machine Learning (ML) methods for unstructured content, including foundation models and large language models.</li><li> Cloud Platforms and Databases: Experience working with cloud platforms (e.g. Kubernetes, AWS, Azure, GCP) and related services, as well as relational and NoSQL databases (SQL, Postgres, DB2, MongoDB).<br/><br/></li></ul><strong>Preferred Technical And Professional Experience<br/><br/></strong><ul><li> Familiarity with Modern UI: Familiarity with modern UI frameworks such as Backbone.js, AngularJS, React.js, Ember.js, Bootstrap, and JQuery, with the ability to apply this knowledge in developing AI solutions.</li><li> Understanding of Libraries: Understanding in the usage of libraries such as SciKit Learn, Pandas, Matplotlib, etc., with the ability to apply this knowledge in developing AI solutions.</li><li> Operating Systems Knowledge: Experience working with various operating systems (Linux, Windows, iOS, Android), with the ability to apply this knowledge in developing and deploying AI solutions.</li></ul>
</div>
<li> Design AI Solutions: Architect and deliver AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models, and experience in tools like Github Copilot and Amazon Code Whisperer.</li>
<li> Implement AI Frameworks: Apply strong programming skills, with proficiency in Python and experience with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, to develop and deploy AI models.</li>
<li> AI Frameworks and Tools: Experience working with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, and tools like Github Copilot and Amazon Code Whisperer to develop and deploy AI models.</li>
<li> Programming Skills: Proficiency in Python programming language, with experience in applying programming skills to develop and deploy AI solutions.</li>
<li> Cloud Platforms and Databases: Experience working with cloud platforms (e.g. Kubernetes, AWS, Azure, GCP) and related services, as well as relational and NoSQL databases (SQL, Postgres, DB2, MongoDB).<br/><br/></li>
<strong>Preferred Technical And Professional Experience<br/><br/></strong>
<li> Operating Systems Knowledge: Experience working with various operating systems (Linux, Windows, iOS, Android), with the ability to apply this knowledge in developing and deploying AI solutions.</li>

In [182]:
for tag in job_soup.find_all(string=lambda x: x and "skills" in x.lower()):
    print(tag.parent)

<script type="application/ld+json">
      {"@context":"http://schema.org","@type":"JobPosting","datePosted":"2026-08-25T17:14:58.000Z","description":"&lt;strong&gt;Introduction&lt;br&gt;&lt;br&gt;&lt;/strong&gt;A career in IBM Consulting is built on long-term client relationships and close collaboration worldwide. You’ll work with leading companies across industries, helping them shape their hybrid cloud and AI journeys. With support from our strategic partners, robust IBM technology, and Red Hat, you’ll have the tools to drive meaningful change and accelerate client impact. At IBM Consulting, curiosity fuels success. You’ll be encouraged to challenge the norm, explore new ideas, and create innovative solutions that deliver real results. Our culture of growth and empathy focuses on your long-term career development while valuing your unique skills and experiences.&lt;br&gt;&lt;br&gt;&lt;strong&gt;Your Role And Responsibilities&lt;br&gt;&lt;br&gt;&lt;/strong&gt;As a Data Scientist with expertise in Artificial Intelligence, you will skillfully combine data analysis and business acumen to tackle cognitive computing challenges. You will be responsible for architecting and delivering AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models. Your primary responsibilities will include:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt; Design AI Solutions: Architect and deliver AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models, and experience in tools like Github Copilot and Amazon Code Whisperer.&lt;/li&gt;&lt;li&gt; Develop Cognitive Solutions: Create comprehensive cognitive solutions that effectively process and analyze both structured and unstructured data, utilizing expertise in NLP, ML, and other specialized areas such as Image Processing, Video Processing, Voice Processing, or Watson technologies.&lt;/li&gt;&lt;li&gt; Implement AI Frameworks: Apply strong programming skills, with proficiency in Python and experience with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, to develop and deploy AI models.&lt;/li&gt;&lt;li&gt; Manage AI Project Lifecycle: Oversee the full AI project lifecycle, from research and prototyping to deployment in production environments, ensuring successful project delivery.&lt;/li&gt;&lt;li&gt; Collaborate with Stakeholders: Work with various stakeholders to identify business problems and leverage the power of artificial intelligence for cognitive computing, driving business value through AI-driven solutions.&lt;br&gt;&lt;br&gt;&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Preferred Education&lt;br&gt;&lt;br&gt;&lt;/strong&gt;Master's Degree&lt;br&gt;&lt;br&gt;&lt;strong&gt;Required Technical And Professional Expertise&lt;br&gt;&lt;br&gt;&lt;/strong&gt;&lt;ul&gt;&lt;li&gt; Advanced Analytics Techniques: Exposure to advanced analytics techniques for structured data, including data analysis and interpretation, to inform business decisions and tackle cognitive computing challenges.&lt;/li&gt;&lt;li&gt; AI Frameworks and Tools: Experience working with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, and tools like Github Copilot and Amazon Code Whisperer to develop and deploy AI models.&lt;/li&gt;&lt;li&gt; Programming Skills: Proficiency in Python programming language, with experience in applying programming skills to develop and deploy AI solutions.&lt;/li&gt;&lt;li&gt; NLP and ML Methods: Exposure to Natural Language Processing (NLP) and Machine Learning (ML) methods for unstructured content, including foundation models and large language models.&lt;/li&gt;&lt;li&gt; Cloud Platforms and Databases: Experience working with cloud platforms (e.g. Kubernetes, AWS, Azure, GCP) and related services, as well as relational and NoSQL databases (SQL, Postgres, DB2, MongoDB).&lt;br&gt;&lt;br&gt;&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Preferred Technical And Professional Experience&lt;br&gt;&lt;br&gt;&lt;/strong&gt;&lt;ul&gt;&lt;li&gt; Familiarity with Modern UI: Familiarity with modern UI frameworks such as Backbone.js, AngularJS, React.js, Ember.js, Bootstrap, and JQuery, with the ability to apply this knowledge in developing AI solutions.&lt;/li&gt;&lt;li&gt; Understanding of Libraries: Understanding in the usage of libraries such as SciKit Learn, Pandas, Matplotlib, etc., with the ability to apply this knowledge in developing AI solutions.&lt;/li&gt;&lt;li&gt; Operating Systems Knowledge: Experience working with various operating systems (Linux, Windows, iOS, Android), with the ability to apply this knowledge in developing and deploying AI solutions.&lt;/li&gt;&lt;/ul&gt;","employmentType":"FULL_TIME","hiringOrganization":{"@type":"Organization","name":"IBM","sameAs":"https://www.linkedin.com/company/ibm","logo":"https://media.licdn.com/dms/image/v2/D560BAQGiz5ecgpCtkA/company-logo_200_200/company-logo_200_200/0/1688684715866/ibm_logo?e=2147483647&amp;v=beta&amp;t=yWxQj1oew7nR92bDw8r80j2EiCwx29aNxLZktJYrsWw"},"identifier":{"@type":"PropertyValue","name":"IBM","value":"114150"},"image":"https://media.licdn.com/dms/image/v2/D560BAQGiz5ecgpCtkA/company-logo_100_100/company-logo_100_100/0/1688684715866/ibm_logo?e=2147483647&amp;v=beta&amp;t=HPSmWLOCvdPkWO1nRWwjjmCNpaCqww20rSJ4E54QtxQ","industry":"IT Services and IT Consulting","jobLocation":{"@type":"Place","address":{"@type":"PostalAddress","addressCountry":"IN","addressLocality":"Kochi","addressRegion":null,"streetAddress":null},"latitude":9.957617,"longitude":76.25115},"skills":"","title":"Data Scientist-Artificial Intelligence","validThrough":"2026-10-02T20:27:31.000Z","educationRequirements":{"@type":"EducationalOccupationalCredential","credentialCategory":"bachelor degree"}}
    </script>
<div class="show-more-less-html__markup show-more-less-html__markup--clamp-after-5 relative overflow-hidden">
<strong>Introduction<br/><br/></strong>A career in IBM Consulting is built on long-term client relationships and close collaboration worldwide. You’ll work with leading companies across industries, helping them shape their hybrid cloud and AI journeys. With support from our strategic partners, robust IBM technology, and Red Hat, you’ll have the tools to drive meaningful change and accelerate client impact. At IBM Consulting, curiosity fuels success. You’ll be encouraged to challenge the norm, explore new ideas, and create innovative solutions that deliver real results. Our culture of growth and empathy focuses on your long-term career development while valuing your unique skills and experiences.<br/><br/><strong>Your Role And Responsibilities<br/><br/></strong>As a Data Scientist with expertise in Artificial Intelligence, you will skillfully combine data analysis and business acumen to tackle cognitive computing challenges. You will be responsible for architecting and delivering AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models. Your primary responsibilities will include:<br/><br/><ul><li> Design AI Solutions: Architect and deliver AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models, and experience in tools like Github Copilot and Amazon Code Whisperer.</li><li> Develop Cognitive Solutions: Create comprehensive cognitive solutions that effectively process and analyze both structured and unstructured data, utilizing expertise in NLP, ML, and other specialized areas such as Image Processing, Video Processing, Voice Processing, or Watson technologies.</li><li> Implement AI Frameworks: Apply strong programming skills, with proficiency in Python and experience with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, to develop and deploy AI models.</li><li> Manage AI Project Lifecycle: Oversee the full AI project lifecycle, from research and prototyping to deployment in production environments, ensuring successful project delivery.</li><li> Collaborate with Stakeholders: Work with various stakeholders to identify business problems and leverage the power of artificial intelligence for cognitive computing, driving business value through AI-driven solutions.<br/><br/></li></ul><strong>Preferred Education<br/><br/></strong>Master's Degree<br/><br/><strong>Required Technical And Professional Expertise<br/><br/></strong><ul><li> Advanced Analytics Techniques: Exposure to advanced analytics techniques for structured data, including data analysis and interpretation, to inform business decisions and tackle cognitive computing challenges.</li><li> AI Frameworks and Tools: Experience working with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, and tools like Github Copilot and Amazon Code Whisperer to develop and deploy AI models.</li><li> Programming Skills: Proficiency in Python programming language, with experience in applying programming skills to develop and deploy AI solutions.</li><li> NLP and ML Methods: Exposure to Natural Language Processing (NLP) and Machine Learning (ML) methods for unstructured content, including foundation models and large language models.</li><li> Cloud Platforms and Databases: Experience working with cloud platforms (e.g. Kubernetes, AWS, Azure, GCP) and related services, as well as relational and NoSQL databases (SQL, Postgres, DB2, MongoDB).<br/><br/></li></ul><strong>Preferred Technical And Professional Experience<br/><br/></strong><ul><li> Familiarity with Modern UI: Familiarity with modern UI frameworks such as Backbone.js, AngularJS, React.js, Ember.js, Bootstrap, and JQuery, with the ability to apply this knowledge in developing AI solutions.</li><li> Understanding of Libraries: Understanding in the usage of libraries such as SciKit Learn, Pandas, Matplotlib, etc., with the ability to apply this knowledge in developing AI solutions.</li><li> Operating Systems Knowledge: Experience working with various operating systems (Linux, Windows, iOS, Android), with the ability to apply this knowledge in developing and deploying AI solutions.</li></ul>
</div>
<li> Implement AI Frameworks: Apply strong programming skills, with proficiency in Python and experience with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, to develop and deploy AI models.</li>
<li> Programming Skills: Proficiency in Python programming language, with experience in applying programming skills to develop and deploy AI solutions.</li>

In [183]:
for tag in job_soup.find_all(string=lambda x: x and "full-time" in x.lower()):
    print(tag.parent)

<span class="description__job-criteria-text description__job-criteria-text--criteria">
            Full-time
          </span>

In [184]:
job_type_tag = job_soup.find(
    "span",
    class_="description__job-criteria-text"
)

print(job_type_tag.get_text(strip=True))

Mid-Senior level

In [185]:
import json

json_ld = job_soup.find(
    "script",
    type="application/ld+json"
)

data = json.loads(json_ld.string)

print(data["employmentType"])
print(data["title"])
print(data["hiringOrganization"]["name"])

FULL_TIME
Data Scientist-Artificial Intelligence
IBM

In [186]:
description = data.get("description", "")

print(description[:1000])

&lt;strong&gt;Introduction&lt;br&gt;&lt;br&gt;&lt;/strong&gt;A career in IBM Consulting is built on long-term client relationships and close collaboration worldwide. You’ll work with leading companies across industries, helping them shape their hybrid cloud and AI journeys. With support from our strategic partners, robust IBM technology, and Red Hat, you’ll have the tools to drive meaningful change and accelerate client impact. At IBM Consulting, curiosity fuels success. You’ll be encouraged to challenge the norm, explore new ideas, and create innovative solutions that deliver real results. Our culture of growth and empathy focuses on your long-term career development while valuing your unique skills and experiences.&lt;br&gt;&lt;br&gt;&lt;strong&gt;Your Role And Responsibilities&lt;br&gt;&lt;br&gt;&lt;/strong&gt;As a Data Scientist with expertise in Artificial Intelligence, you will skillfully combine data analysis and business acumen to tackle cognitive computing challenges. You will

In [187]:
criteria = job_soup.find_all(
    "span",
    class_="description__job-criteria-text"
)

for item in criteria:
    print(item.get_text(strip=True))

Mid-Senior level
Full-time
Engineering and Information Technology
IT Services and IT Consulting

In [188]:
criteria_items = job_soup.find_all(
    "li",
    class_="description__job-criteria-item"
)

for item in criteria_items:
    print(item.get_text(" ", strip=True))

Seniority level Mid-Senior level
Employment type Full-time
Job function Engineering and Information Technology
Industries IT Services and IT Consulting

In [189]:
def extract_criteria(soup):

    experience = None
    job_type = None

    criteria_items = soup.find_all(
        "li",
        class_="description__job-criteria-item"
    )

    for item in criteria_items:

        text = item.get_text(" ", strip=True)

        if "Seniority level" in text:
            value = item.find(
                "span",
                class_="description__job-criteria-text"
            )

            if value:
                experience = value.get_text(strip=True)

        elif "Employment type" in text:
            value = item.find(
                "span",
                class_="description__job-criteria-text"
            )

            if value:
                job_type = value.get_text(strip=True)

    return experience, job_type

In [190]:
experience, job_type = extract_criteria(job_soup)

print("Experience:", experience)
print("Job Type:", job_type)

Experience: Mid-Senior level
Job Type: Full-time

In [191]:
description = data.get("description", "")

print("Description length:", len(description))

Description length: 4549

In [192]:
import json
import re

def extract_job_details(soup):

    experience = None
    job_type = None
    salary = None
    skills = []

    # -------------------------
    # 1. Experience + Job Type
    # -------------------------

    criteria_items = soup.find_all(
        "li",
        class_="description__job-criteria-item"
    )

    for item in criteria_items:

        text = item.get_text(" ", strip=True)

        value = item.find(
            "span",
            class_="description__job-criteria-text"
        )

        if not value:
            continue

        value = value.get_text(strip=True)

        if "Seniority level" in text:
            experience = value

        elif "Employment type" in text:
            job_type = value

    # -------------------------
    # 2. JSON-LD data
    # -------------------------

    json_ld = soup.find(
        "script",
        type="application/ld+json"
    )

    data = {}

    if json_ld:
        try:
            data = json.loads(json_ld.string)
        except:
            data = {}

    description = data.get("description", "")

    # -------------------------
    # 3. Salary
    # -------------------------

    salary_tag = soup.find(
        class_=re.compile("salary", re.I)
    )

    if salary_tag:
        salary = salary_tag.get_text(" ", strip=True)

    # -------------------------
    # 4. Skills
    # -------------------------

    skill_list = [
        "Python",
        "SQL",
        "R",
        "Java",
        "C++",
        "JavaScript",
        "Machine Learning",
        "Deep Learning",
        "Artificial Intelligence",
        "NLP",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "Hugging Face",
        "Pandas",
        "NumPy",
        "Scikit-learn",
        "Matplotlib",
        "Power BI",
        "Tableau",
        "AWS",
        "Azure",
        "GCP",
        "Docker",
        "Kubernetes",
        "Spark",
        "Databricks",
        "MongoDB",
        "PostgreSQL",
        "Git"
    ]

    for skill in skill_list:

        if re.search(
            r"\b" + re.escape(skill) + r"\b",
            description,
            re.IGNORECASE
        ):
            skills.append(skill)

    return {
        "experience": experience,
        "salary": salary,
        "skills": ", ".join(skills) if skills else None,
        "job_type": job_type
    }

In [193]:
job_soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta content="d_jobs_guest_details" name="pageKey"/>
<meta content="max-image-preview:large, noarchive" name="robots"/>
<meta content="max-image-preview:large, archive" name="bingbot"/>
<!-- --><!-- --> <meta content="en_US" name="locale"/>
<!-- --> <meta data-app-version="2.0.3115" data-browser-id="50746ab1-b5ab-45c1-8a7b-fc516e8f8884" data-call-tree-id="AAZZ8jfNIn1/nMJYwC+4mQ==" data-dfp-member-lix-treatment="control" data-disable-jsbeacon-pagekey-suffix="false" data-dna-member-lix-treatment="enabled" data-enable-page-view-heartbeat-tracking="" data-human-member-lix-treatment="enabled" data-is-bot="false" data-is-epd-audit-event-enabled="false" data-is-feed-sponsored-tracking-kill-switch-enabled="false" data-member-id="0" data-multiproduct-name="jobs-guest-frontend" data-network-interceptor-lix-value="control" data-page-instance="urn:li:page:d_jobs_guest_details;IfcUPEylSn+rrTDott7u7A==" data-recaptcha-v3-integration-lix-value="control" data-sequence-auto-redirect-before-request-enabled="true" data-service-name="jobs-guest-frontend" data-should-use-full-url-in-pve-path="true" data-sync-apfc-cb-lix-treatment="control" data-sync-apfc-headers-lix-treatment="control" id="config"/>
<link href="https://in.linkedin.com/jobs/view/data-scientist-artificial-intelligence-at-ibm-4446241710" rel="canonical"/>
<!-- --><!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<link href="https://static.licdn.com/aero-v1/sc/h/al2o9zrvru7aqj8e1x2rzsrca" rel="icon"/>
<script>
          function getDfd() {let yFn,nFn;const p=new Promise(function(y, n){yFn=y;nFn=n;});p.resolve=yFn;p.reject=nFn;return p;}
          window.lazyloader = getDfd();
          window.tracking = getDfd();
          window.impressionTracking = getDfd();
          window.ingraphTracking = getDfd();
          window.appDetection = getDfd();
          window.pemTracking = getDfd();
          window.appRedirectCompleted = getDfd();
        </script>
<!-- -->
<title>IBM hiring Data Scientist-Artificial Intelligence in Kochi, Kerala, India | LinkedIn</title>
<meta content="Posted 5:14:58 PM. IntroductionA career in IBM Consulting is built on long-term client relationships and close…See this and similar jobs on LinkedIn." name="description"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="jobs-guest-frontend" name="litmsProfileName"/>
<meta content="1" data-counter-metric-endpoint="/jobs-guest/api/ingraphs/counter" data-gauge-metric-endpoint="/jobs-guest/api/ingraphs/gauge" name="clientSideIngraphs"/>
<meta charset="utf-8"/>
<meta content="website" property="og:type"/>
<meta content="IBM hiring Data Scientist-Artificial Intelligence in Kochi, Kerala, India | LinkedIn" property="og:title"/>
<meta content="https://in.linkedin.com/jobs/view/data-scientist-artificial-intelligence-at-ibm-4446241710" property="og:url"/>
<meta content="Posted 5:14:58 PM. IntroductionA career in IBM Consulting is built on long-term client relationships and close…See this and similar jobs on LinkedIn." property="og:description"/>
<meta content="https://static.licdn.com/aero-v1/sc/h/xlk678jv0tjp79pv10kglzkf" property="og:image"/>
<meta content="https://static.licdn.com/aero-v1/sc/h/xlk678jv0tjp79pv10kglzkf" name="twitter:image"/>
<meta content="IBM hiring Data Scientist-Artificial Intelligence in Kochi, Kerala, India | LinkedIn" name="twitter:title"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@LinkedIn" name="twitter:site"/>
<meta content="Posted 5:14:58 PM. IntroductionA career in IBM Consulting is built on long-term client relationships and close…See this and similar jobs on LinkedIn." name="twitter:description"/>
<meta content="#293e49" name="theme-color"/>
<meta content="25190" name="titleId"/>
<meta content="1009" name="companyId"/>
<meta content="96" name="industryIds"/>
<meta content="https://in.linkedin.com/jobs/view/data-scientist-artificial-intelligence-at-ibm-4446241710?position=1&amp;pageNum=0&amp;refId=x8S%2B68uVhJjbnbv4CmsPww%3D%3D&amp;trackingId=SvOZkJNmAmrAO7HXXxVCQg%3D%3D" property="lnkd:url"/>
<script type="application/ld+json">
      {"@context":"http://schema.org","@type":"JobPosting","datePosted":"2026-08-25T17:14:58.000Z","description":"&lt;strong&gt;Introduction&lt;br&gt;&lt;br&gt;&lt;/strong&gt;A career in IBM Consulting is built on long-term client relationships and close collaboration worldwide. You’ll work with leading companies across industries, helping them shape their hybrid cloud and AI journeys. With support from our strategic partners, robust IBM technology, and Red Hat, you’ll have the tools to drive meaningful change and accelerate client impact. At IBM Consulting, curiosity fuels success. You’ll be encouraged to challenge the norm, explore new ideas, and create innovative solutions that deliver real results. Our culture of growth and empathy focuses on your long-term career development while valuing your unique skills and experiences.&lt;br&gt;&lt;br&gt;&lt;strong&gt;Your Role And Responsibilities&lt;br&gt;&lt;br&gt;&lt;/strong&gt;As a Data Scientist with expertise in Artificial Intelligence, you will skillfully combine data analysis and business acumen to tackle cognitive computing challenges. You will be responsible for architecting and delivering AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models. Your primary responsibilities will include:&lt;br&gt;&lt;br&gt;&lt;ul&gt;&lt;li&gt; Design AI Solutions: Architect and deliver AI solutions using cutting-edge technologies, with a strong focus on foundation models and large language models, and experience in tools like Github Copilot and Amazon Code Whisperer.&lt;/li&gt;&lt;li&gt; Develop Cognitive Solutions: Create comprehensive cognitive solutions that effectively process and analyze both structured and unstructured data, utilizing expertise in NLP, ML, and other specialized areas such as Image Processing, Video Processing, Voice Processing, or Watson technologies.&lt;/li&gt;&lt;li&gt; Implement AI Frameworks: Apply strong programming skills, with proficiency in Python and experience with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, to develop and deploy AI models.&lt;/li&gt;&lt;li&gt; Manage AI Project Lifecycle: Oversee the full AI project lifecycle, from research and prototyping to deployment in production environments, ensuring successful project delivery.&lt;/li&gt;&lt;li&gt; Collaborate with Stakeholders: Work with various stakeholders to identify business problems and leverage the power of artificial intelligence for cognitive computing, driving business value through AI-driven solutions.&lt;br&gt;&lt;br&gt;&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Preferred Education&lt;br&gt;&lt;br&gt;&lt;/strong&gt;Master's Degree&lt;br&gt;&lt;br&gt;&lt;strong&gt;Required Technical And Professional Expertise&lt;br&gt;&lt;br&gt;&lt;/strong&gt;&lt;ul&gt;&lt;li&gt; Advanced Analytics Techniques: Exposure to advanced analytics techniques for structured data, including data analysis and interpretation, to inform business decisions and tackle cognitive computing challenges.&lt;/li&gt;&lt;li&gt; AI Frameworks and Tools: Experience working with AI frameworks such as TensorFlow, PyTorch, Keras, or Hugging Face, and tools like Github Copilot and Amazon Code Whisperer to develop and deploy AI models.&lt;/li&gt;&lt;li&gt; Programming Skills: Proficiency in Python programming language, with experience in applying programming skills to develop and deploy AI solutions.&lt;/li&gt;&lt;li&gt; NLP and ML Methods: Exposure to Natural Language Processing (NLP) and Machine Learning (ML) methods for unstructured content, including foundation models and large language models.&lt;/li&gt;&lt;li&gt; Cloud Platforms and Databases: Experience working with cloud platforms (e.g. Kubernetes, AWS, Azure, GCP) and related services, as well as relational and NoSQL databases (SQL, Postgres, DB2, MongoDB).&lt;br&gt;&lt;br&gt;&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Preferred Technical And Professional Experience&lt;br&gt;&lt;br&gt;&lt;/strong&gt;&lt;ul&gt;&lt;li&gt; Familiarity with Modern UI: Familiarity with modern UI frameworks such as Backbone.js, AngularJS, React.js, Ember.js, Bootstrap, and JQuery, with the ability to apply this knowledge in developing AI solutions.&lt;/li&gt;&lt;li&gt; Understanding of Libraries: Understanding in the usage of libraries such as SciKit Learn, Pandas, Matplotlib, etc., with the ability to apply this knowledge in developing AI solutions.&lt;/li&gt;&lt;li&gt; Operating Systems Knowledge: Experience working with various operating systems (Linux, Windows, iOS, Android), with the ability to apply this knowledge in developing and deploying AI solutions.&lt;/li&gt;&lt;/ul&gt;","employmentType":"FULL_TIME","hiringOrganization":{"@type":"Organization","name":"IBM","sameAs":"https://www.linkedin.com/company/ibm","logo":"https://media.licdn.com/dms/image/v2/D560BAQGiz5ecgpCtkA/company-logo_200_200/company-logo_200_200/0/1688684715866/ibm_logo?e=2147483647&amp;v=beta&amp;t=yWxQj1oew7nR92bDw8r80j2EiCwx29aNxLZktJYrsWw"},"identifier":{"@type":"PropertyValue","name":"IBM","value":"114150"},"image":"https://media.licdn.com/dms/image/v2/D560BAQGiz5ecgpCtkA/company-logo_100_100/company-logo_100_100/0/1688684715866/ibm_logo?e=2147483647&amp;v=beta&amp;t=HPSmWLOCvdPkWO1nRWwjjmCNpaCqww20rSJ4E54QtxQ","industry":"IT Services and IT Consulting","jobLocation":{"@type":"Place","address":{"@type":"PostalAddress","addressCountry":"IN","addressLocality":"Kochi","addressRegion":null,"streetAddress":null},"latitude":9.957617,"longitude":76.25115},"skills":"","title":"Data Scientist-Artificial Intelligence","validThrough":"2026-10-02T20:27:31.000Z","educationRequirements":{"@type":"EducationalOccupationalCredential","credentialCategory":"bachelor degree"}}
    </script>
<!-- -->
<link href="https://static.licdn.com/aero-v1/sc/h/c5ogjzq9kv7caocfswogqds0k" rel="stylesheet"/>
<!-- --> </head>
<body dir="ltr">
<!-- --><!-- --><!-- -->
<!-- -->
<!-- -->
<a class="skip-link btn-md btn-primary absolute z-11 -top-[100vh] focus:top-0" href="#main-content">
      Skip to main content
    </a>
<header class="header base-detail-page__header px-mobile-container-padding bg-color-background-container global-alert-offset sticky-header">
<nav aria-label="Primary" class="nav pt-1.5 pb-2 flex items-center justify-between relative flex-nowrap babymamabear:py-1.5 nav--minified-mobile">
<a class="nav__logo-link link-no-visited-state z-1 mr-auto min-h-[52px] flex items-center babybear:z-0 hover:no-underline focus:no-underline active:no-underline babymamabear:mr-3" data-tracking-control-name="public_jobs_nav-header-logo" data-tracking-will-navigate="" href="/?trk=public_jobs_nav-header-logo">
<span class="sr-only">LinkedIn</span>
<icon class="nav-logo--inbug flex text-color-brand papabear:hidden mamabear:hidden" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/4zqr0f9jf98vi2nkijyc3bex2" data-svg-class-name="h-[34px] w-[34px] babybear:h-[26px] babybear:w-[26px]"></icon>
<icon class="block text-color-brand w-[102px] h-[26px] babybear:hidden" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/8fkga714vy9b2wk5auqo5reeb" data-test-id="nav-logo"></icon>
</a>
<section class="search-bar relative flex flex-grow h-[40px] bg-cool-gray-20 min-w-0 max-w-full mx-4 rounded-sm babymamabear:mx-0 babymamabear:mb-1.5 babymamabear:bg-color-transparent babymamabear:w-full babymamabear:flex babymamabear:flex-wrap search-bar--minified-mobile" data-current-search-type="JOBS">
<button class="search-bar__placeholder papabear:hidden text-input w-full mt-1.5 !pl-[14px] border-1 border-solid border-color-border-faint rounded-[2px] h-[40px] max-h-[40px] flex items-center overflow-hidden cursor-text" data-tracking-control-name="public_jobs_search-switcher-opener">
<icon class="text-color-icon w-3 h-3 mr-1" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/397vrsk6op88l4981ji1xe1qt"></icon>
<div class="search-bar__full-placeholder font-sans text-md text-color-text max-w-[calc(100%-40px)] text-left whitespace-nowrap overflow-hidden text-ellipsis">
<!-- -->              Data Scientist-Artificial Intelligence in Hyderabad
<!-- --><!-- --> </div>
<span class="sr-only">Expand search</span>
</button>
<div class="switcher-tabs__trigger-and-tabs babymamabear:flex">
<button aria-describedby="switcher-description" aria-expanded="false" class="switcher-tabs__placeholder flex !h-full !py-0 !pl-2 !pr-1.5 border-r-1 border-solid border-r-color-border-faint babymamabear:hidden tab-md papabear:tab-vertical papabear:justify-start cursor-pointer" data-tracking-control-name="public_jobs_switcher-tabs-placeholder">
<span class="switcher-tabs__placeholder-text m-auto"></span>
<icon class="switcher-tabs__caret-down-filled onload pointer-events-none block my-auto min-h-[24px] min-w-[24px] h-[24px] babymamabear:hidden" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/1mbz49mpng9yvv8gqs11n7dkx"></icon>
</button>
<div class="hidden" id="switcher-description">This button displays the currently selected search type. When expanded it provides a list of search options that will switch the search inputs to match the current selection. </div>
<!-- --> <div class="switcher-tabs hidden z-[1] w-auto min-w-[160px] mb-1.5 py-1 absolute top-[48px] left-0 border-solid border-1 border-color-border-faint papabear:container-raised babymamabear:static babymamabear:w-[100vw] babymamabear:h-[48px] babymamabear:p-0 overflow-y-hidden overflow-x-auto md:overflow-x-hidden">
<ul class="switcher-tabs__list flex flex-1 items-stretch papabear:flex-col" role="tablist">
<li class="switcher-tabs__tab h-[44px] babymamabear:basis-1/2" role="presentation">
<button aria-controls="jobs-search-panel" aria-selected="true" class="switcher-tabs__button w-full h-full tab-md papabear:tab-vertical papabear:justify-start cursor-pointer tab-selected" data-switcher-type="JOBS" data-tracking-control-name="public_jobs_switcher-tabs-jobs-search-switcher" id="job-switcher-tab" role="tab">
                        Jobs
                    </button>
</li>
<li class="switcher-tabs__tab h-[44px] babymamabear:basis-1/2" role="presentation">
<button aria-controls="people-search-panel" aria-selected="false" class="switcher-tabs__button w-full h-full tab-md papabear:tab-vertical papabear:justify-start cursor-pointer" data-switcher-type="PEOPLE" data-tracking-control-name="public_jobs_switcher-tabs-people-search-switcher" id="people-switcher-tab" role="tab">
                        People
                    </button>
</li>
<li class="switcher-tabs__tab h-[44px] babymamabear:basis-1/2" role="presentation">
<button aria-controls="learning-search-panel" aria-selected="false" class="switcher-tabs__button w-full h-full tab-md papabear:tab-vertical papabear:justify-start cursor-pointer" data-switcher-type="LEARNING" data-tracking-control-name="public_jobs_switcher-tabs-learning-search-switcher" id="learning-switcher-tab" role="tab">
                        Learning
                    </button>
</li>
</ul>
<button aria-label="Close" class="switcher-tabs__cancel-btn papabear:hidden block w-6 h-6 m-auto text-color-text-low-emphasis" data-tracking-control-name="public_jobs_switcher-tabs-cancel-search-switcher" type="button">
<icon class="switcher-tabs__cancel-icon block w-3 h-3 m-auto onload" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/cs55jggk4p3uqh9ozxdmpvjg7"></icon>
</button>
</div>
</div>
<section aria-labelledby="people-switcher-tab" class="base-search-bar w-full h-full" data-searchbar-type="PEOPLE" id="people-search-panel" role="tabpanel">
<form action="/pub/dir" class="base-search-bar__form w-full flex babymamabear:mx-mobile-container-padding babymamabear:flex-col" data-tracking-control-name="public_jobs_people-search-bar_base-search-bar-form" role="search">
<section class="dismissable-input text-input !pr-3 bg-color-transparent flex items-center h-[40px] min-w-0 relative babybear:w-full babybear:mb-1 search-input">
<input aria-label="First Name" autocomplete="on" class="dismissable-input__input font-sans text-md text-color-text bg-color-transparent flex items-center flex-1 focus:outline-none placeholder:text-color-text-secondary" data-tracking-control-name="public_jobs_people-search-bar_first-name_dismissable-input" maxlength="500" name="firstName" placeholder="First Name" type="search"/>
<button class="dismissable-input__button text-color-text h-[40px] min-w-[24px] w-[24px] -mr-2 opacity-0 transition-opacity duration-[0.1s] disabled:invisible focus:opacity-100" data-tracking-control-name="public_jobs_people-search-bar_first-name_dismissable-input-clear" type="button">
<label class="sr-only">Clear text</label>
<icon class="dismissable-input__button-icon" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/cs55jggk4p3uqh9ozxdmpvjg7"></icon>
</button>
</section>
<section class="dismissable-input text-input !pr-3 bg-color-transparent flex items-center h-[40px] min-w-0 relative babybear:w-full babybear:mb-1 search-input">
<input aria-label="Last Name" autocomplete="on" class="dismissable-input__input font-sans text-md text-color-text bg-color-transparent flex items-center flex-1 focus:outline-none placeholder:text-color-text-secondary" data-tracking-control-name="public_jobs_people-search-bar_last-name_dismissable-input" maxlength="500" name="lastName" placeholder="Last Name" type="search"/>
<button class="dismissable-input__button text-color-text h-[40px] min-w-[24px] w-[24px] -mr-2 opacity-0 transition-opacity duration-[0.1s] disabled:invisible focus:opacity-100" data-tracking-control-name="public_jobs_people-search-bar_last-name_dismissable-input-clear" type="button">
<label class="sr-only">Clear text</label>
<icon class="dismissable-input__button-icon" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/cs55jggk4p3uqh9ozxdmpvjg7"></icon>
</button>
</section>
<input name="trk" type="hidden" value="public_jobs_people-search-bar_search-submit"/>
<button aria-label="Search" class="base-search-bar__submit-btn block basis-[40px] flex-shrink-0 cursor-pointer babymamabear:invisible babymamabear:ml-[-9999px] babymamabear:w-[1px] babymamabear:h-[1px]" data-tracking-control-name="public_jobs_people-search-bar_base-search-bar-search-submit" type="submit">
<icon class="base-search-bar__search-icon onload mx-auto" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/cb5bsr4tsn2r4sjg9e3ls4tjl"></icon>
</button>
</form>
</section>
<section aria-labelledby="job-switcher-tab" class="base-search-bar w-full h-full" data-searchbar-type="JOBS" id="jobs-search-panel" role="tabpanel">
<form action="/jobs/search" class="base-search-bar__form w-full flex babymamabear:mx-mobile-container-padding babymamabear:flex-col" data-tracking-control-name="public_jobs_jobs-search-bar_base-search-bar-form" role="search">
<code id="i18n_aria_live_text_no-suggestions" style="display: none"><!--"No suggestions found"--></code>
<code id="i18n_aria_live_text_one-suggestion" style="display: none"><!--"One Suggestion. Use up and down keys to navigate"--></code>
<code id="i18n_aria_live_text_multiple-suggestions" style="display: none"><!--"Multiple Suggestions. Use up and down keys to navigate"--></code>
<section class="dismissable-input text-input !pr-3 bg-color-transparent flex items-center h-[40px] min-w-0 relative babybear:w-full babybear:mb-1 typeahead-input keywords-typeahead-input text-input">

In [194]:
details = extract_job_details(job_soup)

print(details)

{'experience': 'Mid-Senior level', 'salary': '₹1,000,000.00\n            -\n            ₹3,000,000.00', 'skills': 'Python, SQL, Machine Learning, Artificial Intelligence, NLP, TensorFlow, PyTorch, Keras, Hugging Face, Pandas, Matplotlib, AWS, Azure, GCP, Kubernetes, MongoDB', 'job_type': 'Full-time'}

In [195]:
def get_job_details(job_url):

    try:
        response = requests.get(
            job_url,
            headers=headers,
            timeout=20
        )

        if response.status_code != 200:
            print(
                "Failed:",
                response.status_code,
                job_url
            )
            return {
                "experience": None,
                "salary": None,
                "skills": None,
                "job_type": None
            }

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        return extract_job_details(soup)

    except Exception as e:

        print("Error:", e)

        return {
            "experience": None,
            "salary": None,
            "skills": None,
            "job_type": None
        }

In [196]:
test_details = get_job_details(
    df.loc[0, "job_url"]
)

print(test_details)

{'experience': 'Mid-Senior level', 'salary': '₹1,000,000.00\n            -\n            ₹3,000,000.00', 'skills': 'Python, SQL, Machine Learning, Artificial Intelligence, NLP, TensorFlow, PyTorch, Keras, Hugging Face, Pandas, Matplotlib, AWS, Azure, GCP, Kubernetes, MongoDB', 'job_type': 'Full-time'}

In [197]:
test_details = get_job_details(
    df.loc[0, "job_url"]
)

print(test_details)

{'experience': 'Mid-Senior level', 'salary': '₹1,000,000.00\n            -\n            ₹3,000,000.00', 'skills': 'Python, SQL, Machine Learning, Artificial Intelligence, NLP, TensorFlow, PyTorch, Keras, Hugging Face, Pandas, Matplotlib, AWS, Azure, GCP, Kubernetes, MongoDB', 'job_type': 'Full-time'}

In [198]:
df["experience"] = None
df["salary"] = None
df["skills"] = None
df["job_type"] = None

print(df.columns)

Index(['title', 'company', 'location', 'job_url', 'posted_text', 'posted_date',
       'experience', 'salary', 'skills', 'job_type'],
      dtype='str')

In [199]:
import time

for i in range(10):

    print("Processing:", i + 1)

    details = get_job_details(
        df.loc[i, "job_url"]
    )

    df.loc[i, "experience"] = details["experience"]
    df.loc[i, "salary"] = details["salary"]
    df.loc[i, "skills"] = details["skills"]
    df.loc[i, "job_type"] = details["job_type"]

    time.sleep(10)

Processing: 1

Processing: 2
Processing: 3
Processing: 4
Processing: 5
Processing: 6
Processing: 7
Processing: 8
Processing: 9
Processing: 10

In [200]:
df[
    [
        "title",
        "company",
        "experience",
        "salary",
        "skills",
        "job_type"
    ]
].head(10)

,title,company,experience,salary,skills,job_type
0,Data Scientist-Artificial Intelligence,IBM,Mid-Senior level,"₹1,000,000.00\n -\n ₹3,0...","Python, SQL, Machine Learning, Artificial Inte...",Full-time
1,Senior Data Scientist - I,MetLife,Mid-Senior level,None,"Python, Machine Learning, NLP, TensorFlow, PyT...",Full-time
2,Senior Data Scientist,SourcingXPress,Mid-Senior level,"Base pay range ₹2,000,000.00/yr - ₹4,000,000.0...","Python, Machine Learning, Deep Learning, AWS, ...",Full-time
3,Sr Advanced Data Scientist,Honeywell Technologies,Mid-Senior level,None,"Python, R, Machine Learning, Azure, Databricks",Full-time
4,Senior Data Scientist I,MetLife,Mid-Senior level,None,"Python, Machine Learning, NLP, TensorFlow, PyT...",Full-time
5,Senior Data Scientist,Amplify Health,Mid-Senior level,"₹2,000,000.00\n -\n ₹4,0...","Python, SQL, Machine Learning, Deep Learning, ...",Full-time
6,Senior Data Scientist,SEI,Mid-Senior level,"₹4,000,000.00\n -\n ₹5,5...","Python, SQL, R, Machine Learning, Artificial I...",Full-time
7,Lead Data Scientist,AtkinsRéalis,Mid-Senior level,"₹1,000,000.00\n -\n ₹3,0...","Python, Machine Learning, Deep Learning, Tenso...",Full-time
8,Data Scientist - Machine Learning,United Airlines India Knowledge Center,Mid-Senior level,"₹1,200,000.00\n -\n ₹1,8...","Python, SQL, Machine Learning, Artificial Inte...",Full-time
9,Lead Data Scientist- Gen AI-ML- Vice president,Citi,Not Applicable,None,"Python, SQL, Machine Learning, NLP, TensorFlow...",Full-time

In [205]:
df.to_csv(
    "linkedin_jobs_with_details.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [ ]:
df[["title", "experience", "salary", "job_type"]].head(10)

,title,experience,salary,job_type
0,Data Scientist-Artificial Intelligence,Mid-Senior level,"₹1,000,000.00\n -\n ₹3,0...",Full-time
1,Senior Data Scientist - I,Mid-Senior level,None,Full-time
2,Senior Data Scientist,Mid-Senior level,"Base pay range ₹2,000,000.00/yr - ₹4,000,000.0...",Full-time
3,Sr Advanced Data Scientist,Mid-Senior level,None,Full-time
4,Senior Data Scientist I,Mid-Senior level,None,Full-time
5,Senior Data Scientist,Mid-Senior level,"₹2,000,000.00\n -\n ₹4,0...",Full-time
6,Senior Data Scientist,Mid-Senior level,"₹4,000,000.00\n -\n ₹5,5...",Full-time
7,Lead Data Scientist,Mid-Senior level,"₹1,000,000.00\n -\n ₹3,0...",Full-time
8,Senior Data Scientist (Remote),Mid-Senior level,"₹4,000,000.00\n -\n ₹5,5...",Full-time
9,Data Scientist - Machine Learning,Mid-Senior level,"₹1,200,000.00\n -\n ₹1,8...",Full-time

In [ ]:
import time

for i in range(10, 20):

    print("Processing:", i + 1)

    details = get_job_details(
        df.loc[i, "job_url"]
    )

    df.loc[i, "experience"] = details["experience"]
    df.loc[i, "salary"] = details["salary"]
    df.loc[i, "skills"] = details["skills"]
    df.loc[i, "job_type"] = details["job_type"]

    time.sleep(10)

print("Batch complete!")

Processing: 11
Processing: 12
Processing: 13
Processing: 14
Processing: 15
Processing: 16
Processing: 17
Processing: 18
Processing: 19
Processing: 20
Batch complete!

In [206]:
df.to_csv(
    "linkedin_jobs_with_details.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [207]:
print(
    "Experience found:",
    df["experience"].notna().sum()
)

print(
    "Salary found:",
    df["salary"].notna().sum()
)

print(
    "Skills found:",
    df["skills"].notna().sum()
)

print(
    "Job type found:",
    df["job_type"].notna().sum()
)

Experience found: 10
Salary found: 6
Skills found: 10
Job type found: 10

In [208]:
print("Experience:", df["experience"].notna().sum())
print("Salary:", df["salary"].notna().sum())
print("Skills:", df["skills"].notna().sum())
print("Job type:", df["job_type"].notna().sum())

Experience: 10
Salary: 6
Skills: 10
Job type: 10

In [210]:
import time

for i in range(10, 20):

    print("Processing:", i + 1)

    details = get_job_details(
        df.loc[i, "job_url"]
    )

    df.loc[i, "experience"] = details["experience"]
    df.loc[i, "salary"] = details["salary"]
    df.loc[i, "skills"] = details["skills"]
    df.loc[i, "job_type"] = details["job_type"]

    time.sleep(10)

print("Batch complete!")

Processing: 11
Processing: 12
Processing: 13
Processing: 14
Processing: 15
Processing: 16
Processing: 17
Processing: 18
Processing: 19
Processing: 20
Batch complete!

In [211]:
df.to_csv(
    "linkedin_jobs_with_details_v2.csv",
    index=False
)

print("Saved:", len(df), "jobs")

Saved: 600 jobs

In [212]:
print("Processed experience:", df["experience"].notna().sum())
print("Salary available:", df["salary"].notna().sum())
print("Skills found:", df["skills"].notna().sum())
print("Job type found:", df["job_type"].notna().sum())

Processed experience: 20
Salary available: 12
Skills found: 20
Job type found: 20

In [213]:
df["experience"] = None
df["salary"] = None
df["skills"] = None
df["job_type"] = None

In [214]:
for i, job_url in enumerate(df["job_url"]):

    print(f"Processing {i + 1}/{len(df)}")

    details = get_job_details(job_url)

    df.loc[i, "experience"] = details["experience"]
    df.loc[i, "salary"] = details["salary"]
    df.loc[i, "skills"] = details["skills"]
    df.loc[i, "job_type"] = details["job_type"]

    # Save every 20 jobs
    if (i + 1) % 20 == 0:
        df.to_csv(
            "linkedin_jobs_with_details_v2.csv",
            index=False
        )
        print("Progress saved:", i + 1)

Processing 1/600
Processing 2/600
Processing 3/600
Processing 4/600
Processing 5/600
Processing 6/600
Processing 7/600
Processing 8/600
Processing 9/600
Processing 10/600
Processing 11/600
Processing 12/600
Processing 13/600
Processing 14/600
Processing 15/600
Processing 16/600
Processing 17/600
Processing 18/600
Processing 19/600
Processing 20/600
Progress saved: 20
Processing 21/600
Processing 22/600
Processing 23/600
Processing 24/600
Processing 25/600
Processing 26/600
Processing 27/600
Processing 28/600
Processing 29/600
Processing 30/600
Processing 31/600
Processing 32/600
Failed: 429 https://in.linkedin.com/jobs/view/principal-data-scientist-at-jaggaer-4451521110?position=32&pageNum=0&refId=x8S%2B68uVhJjbnbv4CmsPww%3D%3D&trackingId=fGGn4bTXtPgefkIQr8rgDA%3D%3D
Processing 33/600
Processing 34/600
Processing 35/600
Processing 36/600
Processing 37/600
Processing 38/600
Processing 39/600
Processing 40/600
Progress saved: 40
Processing 41/600
Processing 42/600
Processing 43/600
Processing 44/600
Processing 45/600
Processing 46/600
Processing 47/600
Processing 48/600
Processing 49/600
Processing 50/600
Processing 51/600
Processing 52/600
Processing 53/600
Processing 54/600
Failed: 429 https://in.linkedin.com/jobs/view/principal-data-scientist-digital-health-at-alcon-4450090718?position=54&pageNum=0&refId=x8S%2B68uVhJjbnbv4CmsPww%3D%3D&trackingId=gQ1pNACjSXMRtE1yjB%2F2Gg%3D%3D
Processing 55/600
Processing 56/600
Processing 57/600
Processing 58/600
Processing 59/600
Processing 60/600
Progress saved: 60
Processing 61/600
Processing 62/600
Processing 63/600
Processing 64/600
Processing 65/600
Processing 66/600
Processing 67/600
Processing 68/600
Processing 69/600
Processing 70/600
Processing 71/600
Processing 72/600
Processing 73/600
Processing 74/600
Processing 75/600
Processing 76/600
Processing 77/600
Processing 78/600
Processing 79/600
Processing 80/600
Progress saved: 80
Processing 81/600
Processing 82/600
Processing 83/600
Processing 84/600
Processing 85/600
Processing 86/600
Processing 87/600
Processing 88/600
Processing 89/600
Processing 90/600
Processing 91/600
Processing 92/600
Processing 93/600
Processing 94/600
Processing 95/600
Processing 96/600
Processing 97/600
Processing 98/600
Processing 99/600
Processing 100/600
Progress saved: 100
Processing 101/600
Processing 102/600
Processing 103/600
Processing 104/600
Processing 105/600
Processing 106/600
Processing 107/600
Processing 108/600
Processing 109/600
Processing 110/600
Processing 111/600
Processing 112/600
Processing 113/600
Processing 114/600
Processing 115/600
Processing 116/600
Processing 117/600
Processing 118/600
Processing 119/600
Processing 120/600
Progress saved: 120
Processing 121/600
Processing 122/600
Processing 123/600
Processing 124/600
Processing 125/600
Processing 126/600
Processing 127/600
Processing 128/600
Processing 129/600
Processing 130/600
Processing 131/600
Processing 132/600
Processing 133/600
Processing 134/600
Processing 135/600
Processing 136/600
Processing 137/600
Processing 138/600
Processing 139/600
Processing 140/600
Progress saved: 140
Processing 141/600
Processing 142/600
Processing 143/600
Processing 144/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-microsoft-365-copilot-ai-at-vivantify-technology-solutions-india-pvt-ltd-4457401756?position=24&pageNum=0&refId=ffrsjRLuKMIPdDJaQ0lclw%3D%3D&trackingId=jk%2FyU4ikPqblktJ%2FDGHyRQ%3D%3D
Processing 145/600
Processing 146/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-at-celebal-technologies-4453514682?position=26&pageNum=0&refId=ffrsjRLuKMIPdDJaQ0lclw%3D%3D&trackingId=TnOm4mErZiEWDmOlxSw9Rw%3D%3D
Processing 147/600
Processing 148/600
Failed: 429 https://in.linkedin.com/jobs/view/ai-ml-lead-at-vbots-4431042492?position=28&pageNum=0&refId=ffrsjRLuKMIPdDJaQ0lclw%3D%3D&trackingId=LLjMDDZ%2FD8jijapY9k16CQ%3D%3D
Processing 149/600
Processing 150/600
Processing 151/600
Processing 152/600
Processing 153/600
Processing 154/600
Processing 155/600
Processing 156/600
Processing 157/600
Processing 158/600
Processing 159/600
Processing 160/600
Progress saved: 160
Processing 161/600
Processing 162/600
Processing 163/600
Processing 164/600
Processing 165/600
Processing 166/600
Processing 167/600
Processing 168/600
Processing 169/600
Processing 170/600
Processing 171/600
Processing 172/600
Processing 173/600
Processing 174/600
Processing 175/600
Processing 176/600
Processing 177/600
Processing 178/600
Processing 179/600
Processing 180/600
Failed: 429 https://in.linkedin.com/jobs/view/data-architect-gen-ai-at-einfochips-an-arrow-company-4452932683?position=60&pageNum=0&refId=ffrsjRLuKMIPdDJaQ0lclw%3D%3D&trackingId=liudmyIk%2F3u9Vv3ljXK8ow%3D%3D
Progress saved: 180
Processing 181/600
Processing 182/600
Processing 183/600
Processing 184/600
Processing 185/600
Processing 186/600
Processing 187/600
Processing 188/600
Processing 189/600
Processing 190/600
Processing 191/600
Processing 192/600
Processing 193/600
Processing 194/600
Processing 195/600
Processing 196/600
Processing 197/600
Processing 198/600
Processing 199/600
Processing 200/600
Progress saved: 200
Processing 201/600
Processing 202/600
Processing 203/600
Processing 204/600
Processing 205/600
Processing 206/600
Processing 207/600
Processing 208/600
Processing 209/600
Processing 210/600
Processing 211/600
Processing 212/600
Processing 213/600
Processing 214/600
Processing 215/600
Processing 216/600
Processing 217/600
Processing 218/600
Processing 219/600
Processing 220/600
Progress saved: 220
Processing 221/600
Processing 222/600
Processing 223/600
Processing 224/600
Processing 225/600
Processing 226/600
Processing 227/600
Processing 228/600
Processing 229/600
Processing 230/600
Processing 231/600
Processing 232/600
Processing 233/600
Processing 234/600
Processing 235/600
Processing 236/600
Processing 237/600
Processing 238/600
Processing 239/600
Processing 240/600
Progress saved: 240
Processing 241/600
Processing 242/600
Processing 243/600
Processing 244/600
Processing 245/600
Processing 246/600
Processing 247/600
Processing 248/600
Processing 249/600
Processing 250/600
Processing 251/600
Processing 252/600
Processing 253/600
Processing 254/600
Processing 255/600
Processing 256/600
Processing 257/600
Processing 258/600
Processing 259/600
Processing 260/600
Progress saved: 260
Processing 261/600
Processing 262/600
Processing 263/600
Processing 264/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-%E2%80%93-mortgage-analytics-ai-at-loandna-4453688615?position=24&pageNum=0&refId=OLB1k8yVwEvdoL6PBLB7Qg%3D%3D&trackingId=PiS9pBjgoSxdOEQ1Ue2sWw%3D%3D
Processing 265/600
Processing 266/600
Processing 267/600
Processing 268/600
Processing 269/600
Failed: 429 https://in.linkedin.com/jobs/view/senior-data-scientist-at-fourkites-inc-4458585972?position=29&pageNum=0&refId=OLB1k8yVwEvdoL6PBLB7Qg%3D%3D&trackingId=X3%2BDO2c8Y%2FjefQNb1NX95g%3D%3D
Processing 270/600
Processing 271/600
Processing 272/600
Processing 273/600
Processing 274/600
Processing 275/600
Processing 276/600
Processing 277/600
Processing 278/600
Processing 279/600
Processing 280/600
Progress saved: 280
Processing 281/600
Processing 282/600
Processing 283/600
Processing 284/600
Processing 285/600
Processing 286/600
Processing 287/600
Processing 288/600
Processing 289/600
Processing 290/600
Processing 291/600
Processing 292/600
Processing 293/600
Processing 294/600
Processing 295/600
Processing 296/600
Processing 297/600
Processing 298/600
Processing 299/600
Processing 300/600
Progress saved: 300
Processing 301/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-artificial-intelligence-at-ibm-4446241710?position=1&pageNum=0&refId=I3bqPSYc%2BdbHpyUH%2FoISgw%3D%3D&trackingId=xKAyCt5CaWhqEFSodXTCzQ%3D%3D
Processing 302/600
Processing 303/600
Processing 304/600
Processing 305/600
Processing 306/600
Processing 307/600
Processing 308/600
Processing 309/600
Processing 310/600
Processing 311/600
Processing 312/600
Processing 313/600
Processing 314/600
Processing 315/600
Processing 316/600
Processing 317/600
Processing 318/600
Processing 319/600
Failed: 429 https://in.linkedin.com/jobs/view/senior-principal-data-scientist-at-atkinsr%C3%A9alis-4394640162?position=19&pageNum=0&refId=I3bqPSYc%2BdbHpyUH%2FoISgw%3D%3D&trackingId=wzydiPGgvPo4xhnGatqutg%3D%3D
Processing 320/600
Progress saved: 320
Processing 321/600
Failed: 429 https://in.linkedin.com/jobs/view/straviso-senior-data-scientist-machine-learning-at-straviso-4438548274?position=21&pageNum=0&refId=I3bqPSYc%2BdbHpyUH%2FoISgw%3D%3D&trackingId=89ggU4Q%2B8mlBICwCPbslNQ%3D%3D
Processing 322/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-i-at-kroll-4453471229?position=22&pageNum=0&refId=I3bqPSYc%2BdbHpyUH%2FoISgw%3D%3D&trackingId=FRZWvnFkja6XNiTtcydTfw%3D%3D
Processing 323/600
Processing 324/600
Processing 325/600
Processing 326/600
Processing 327/600
Processing 328/600
Processing 329/600
Processing 330/600
Processing 331/600
Processing 332/600
Processing 333/600
Processing 334/600
Processing 335/600
Processing 336/600
Processing 337/600
Processing 338/600
Processing 339/600
Processing 340/600
Progress saved: 340
Processing 341/600
Processing 342/600
Processing 343/600
Processing 344/600
Processing 345/600
Processing 346/600
Processing 347/600
Processing 348/600
Processing 349/600
Processing 350/600
Processing 351/600
Processing 352/600
Processing 353/600
Processing 354/600
Processing 355/600
Processing 356/600
Processing 357/600
Failed: 429 https://in.linkedin.com/jobs/view/lead-data-scientist-at-accenture-in-india-4448345079?position=57&pageNum=0&refId=I3bqPSYc%2BdbHpyUH%2FoISgw%3D%3D&trackingId=l5Jtqz0sZSa7sBJIoM9s8A%3D%3D
Processing 358/600
Processing 359/600
Processing 360/600
Progress saved: 360
Processing 361/600
Processing 362/600
Processing 363/600
Processing 364/600
Processing 365/600
Processing 366/600
Processing 367/600
Processing 368/600
Processing 369/600
Processing 370/600
Processing 371/600
Processing 372/600
Processing 373/600
Processing 374/600
Processing 375/600
Processing 376/600
Processing 377/600
Processing 378/600
Processing 379/600
Processing 380/600
Progress saved: 380
Processing 381/600
Processing 382/600
Processing 383/600
Processing 384/600
Processing 385/600
Processing 386/600
Processing 387/600
Processing 388/600
Processing 389/600
Processing 390/600
Processing 391/600
Processing 392/600
Processing 393/600
Processing 394/600
Processing 395/600
Processing 396/600
Processing 397/600
Processing 398/600
Processing 399/600
Processing 400/600
Progress saved: 400
Processing 401/600
Processing 402/600
Processing 403/600
Processing 404/600
Processing 405/600
Processing 406/600
Processing 407/600
Processing 408/600
Processing 409/600
Processing 410/600
Processing 411/600
Processing 412/600
Processing 413/600
Processing 414/600
Processing 415/600
Processing 416/600
Processing 417/600
Processing 418/600
Processing 419/600
Processing 420/600
Progress saved: 420
Processing 421/600
Processing 422/600
Processing 423/600
Processing 424/600
Processing 425/600
Processing 426/600
Processing 427/600
Processing 428/600
Processing 429/600
Processing 430/600
Processing 431/600
Processing 432/600
Processing 433/600
Processing 434/600
Processing 435/600
Processing 436/600
Processing 437/600
Processing 438/600
Processing 439/600
Processing 440/600
Progress saved: 440
Processing 441/600
Processing 442/600
Processing 443/600
Processing 444/600
Processing 445/600
Processing 446/600
Failed: 429 https://in.linkedin.com/jobs/view/predictive-analytics-data-scientist-ai-labs-at-adani-enterprises-limited-4427055522?position=26&pageNum=0&refId=hZuiqwOOtcQp0Nopt52now%3D%3D&trackingId=%2BFTakmOw9NYgTcPaC9BYbg%3D%3D
Processing 447/600
Processing 448/600
Processing 449/600
Processing 450/600
Processing 451/600
Processing 452/600
Processing 453/600
Processing 454/600
Processing 455/600
Processing 456/600
Processing 457/600
Processing 458/600
Processing 459/600
Processing 460/600
Progress saved: 460
Processing 461/600
Processing 462/600
Processing 463/600
Processing 464/600
Processing 465/600
Processing 466/600
Processing 467/600
Processing 468/600
Failed: 429 https://in.linkedin.com/jobs/view/digital-manager-at-ey-4456528091?position=48&pageNum=0&refId=hZuiqwOOtcQp0Nopt52now%3D%3D&trackingId=%2BSSOcmot9uh6%2FypVri2c8w%3D%3D
Processing 469/600
Processing 470/600
Processing 471/600
Processing 472/600
Processing 473/600
Processing 474/600
Processing 475/600
Processing 476/600
Processing 477/600
Failed: 429 https://in.linkedin.com/jobs/view/lead-data-scientist-at-accenture-in-india-4448345079?position=57&pageNum=0&refId=hZuiqwOOtcQp0Nopt52now%3D%3D&trackingId=tiLtbCRdkSOyqjbGlFjrhQ%3D%3D
Processing 478/600
Failed: 429 https://in.linkedin.com/jobs/view/senior-data-scientist-at-usefulbi-corporation-4448171986?position=58&pageNum=0&refId=hZuiqwOOtcQp0Nopt52now%3D%3D&trackingId=qEnLgutT8nsPEyd6n%2BJ0LQ%3D%3D
Processing 479/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-ii-ultra-at-affle-4450139004?position=59&pageNum=0&refId=hZuiqwOOtcQp0Nopt52now%3D%3D&trackingId=jOqHmLIfxRF0btNA%2FMJHXg%3D%3D
Processing 480/600
Progress saved: 480
Processing 481/600
Processing 482/600
Processing 483/600
Processing 484/600
Processing 485/600
Processing 486/600
Processing 487/600
Processing 488/600
Processing 489/600
Processing 490/600
Processing 491/600
Processing 492/600
Processing 493/600
Processing 494/600
Processing 495/600
Processing 496/600
Processing 497/600
Processing 498/600
Processing 499/600
Processing 500/600
Progress saved: 500
Processing 501/600
Processing 502/600
Processing 503/600
Processing 504/600
Processing 505/600
Processing 506/600
Processing 507/600
Processing 508/600
Processing 509/600
Processing 510/600
Processing 511/600
Processing 512/600
Processing 513/600
Processing 514/600
Processing 515/600
Processing 516/600
Processing 517/600
Processing 518/600
Processing 519/600
Processing 520/600
Progress saved: 520
Processing 521/600
Processing 522/600
Processing 523/600
Processing 524/600
Processing 525/600
Processing 526/600
Processing 527/600
Processing 528/600
Processing 529/600
Processing 530/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-at-bnp-paribas-4452403514?position=50&pageNum=0&refId=1jFvyh9RiZI%2FMc%2Bi5QFy7Q%3D%3D&trackingId=JmoQA8oiRWgO85jrxW8Qwg%3D%3D
Processing 531/600
Processing 532/600
Processing 533/600
Processing 534/600
Processing 535/600
Processing 536/600
Processing 537/600
Processing 538/600
Processing 539/600
Processing 540/600
Progress saved: 540
Processing 541/600
Processing 542/600
Processing 543/600
Processing 544/600
Processing 545/600
Processing 546/600
Processing 547/600
Processing 548/600
Processing 549/600
Processing 550/600
Processing 551/600
Processing 552/600
Processing 553/600
Processing 554/600
Failed: 429 https://in.linkedin.com/jobs/view/machine-learning-engineer-at-simplify-healthcare-4455251418?position=14&pageNum=0&refId=MyAU%2Bu9MPaC%2F0hXS45%2BlKw%3D%3D&trackingId=ms7otTZkIicm%2FbGF7T%2FHZQ%3D%3D
Processing 555/600
Processing 556/600
Processing 557/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-i-at-kroll-4453474215?position=17&pageNum=0&refId=MyAU%2Bu9MPaC%2F0hXS45%2BlKw%3D%3D&trackingId=oD0qU9Bh9kCzbK2AXnsKgQ%3D%3D
Processing 558/600
Processing 559/600
Processing 560/600
Progress saved: 560
Processing 561/600
Processing 562/600
Processing 563/600
Processing 564/600
Processing 565/600
Processing 566/600
Processing 567/600
Processing 568/600
Processing 569/600
Processing 570/600
Processing 571/600
Processing 572/600
Processing 573/600
Processing 574/600
Processing 575/600
Processing 576/600
Processing 577/600
Processing 578/600
Processing 579/600
Failed: 429 https://in.linkedin.com/jobs/view/machine-learning-ai-and-data-science-engineer-iii-at-deloitte-4425095675?position=39&pageNum=0&refId=MyAU%2Bu9MPaC%2F0hXS45%2BlKw%3D%3D&trackingId=T9v%2BUjpwP25dcUHB49guHA%3D%3D
Processing 580/600
Failed: 429 https://in.linkedin.com/jobs/view/senior-data-scientist-at-cognite-4446547646?position=40&pageNum=0&refId=MyAU%2Bu9MPaC%2F0hXS45%2BlKw%3D%3D&trackingId=5pa49TrD%2BUlQ33Nu5%2Bm8Ew%3D%3D
Progress saved: 580
Processing 581/600
Processing 582/600
Processing 583/600
Processing 584/600
Processing 585/600
Processing 586/600
Processing 587/600
Failed: 429 https://in.linkedin.com/jobs/view/analyst-data-scientist-at-united-airlines-india-knowledge-center-4450731636?position=47&pageNum=0&refId=MyAU%2Bu9MPaC%2F0hXS45%2BlKw%3D%3D&trackingId=31u8YYyKB1WFZbKoRB4Vvw%3D%3D
Processing 588/600
Processing 589/600
Processing 590/600
Processing 591/600
Processing 592/600
Failed: 429 https://in.linkedin.com/jobs/view/data-scientist-at-exl-4446724288?position=52&pageNum=0&refId=MyAU%2Bu9MPaC%2F0hXS45%2BlKw%3D%3D&trackingId=bSig%2B4L7NOCCQyBTAOga6Q%3D%3D
Processing 593/600
Failed: 429 https://in.linkedin.com/jobs/view/straviso-data-scientist-artificial-intelligence-machine-learning-at-straviso-4438549287?position=53&pageNum=0&refId=MyAU%2Bu9MPaC%2F0hXS45%2BlKw%3D%3D&trackingId=QC3Efxg2XnSfhv6o6gcyqw%3D%3D
Processing 594/600
Processing 595/600
Processing 596/600
Processing 597/600
Processing 598/600
Processing 599/600
Processing 600/600
Progress saved: 600

In [217]:
def get_job_details(job_url):

    try:
        response = requests.get(
            job_url,
            headers=headers,
            timeout=20
        )

        if response.status_code == 429:
            print("429 RATE LIMIT — STOPPING")
            return None

        if response.status_code != 200:
            return {
                "experience": None,
                "salary": None,
                "skills": None,
                "job_type": None
            }

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        return extract_job_details(soup)

    except Exception as e:
        print("Error:", e)

        return {
            "experience": None,
            "salary": None,
            "skills": None,
            "job_type": None
        }

In [218]:
print("Total rows:", len(df))

print("Experience:", df["experience"].notna().sum())
print("Salary:", df["salary"].notna().sum())
print("Skills:", df["skills"].notna().sum())
print("Job type:", df["job_type"].notna().sum())

Total rows: 600
Experience: 574
Salary: 298
Skills: 566
Job type: 574

In [219]:
df[
    [
        "title",
        "company",
        "experience",
        "salary",
        "skills",
        "job_type"
    ]
].head(20)

,title,company,experience,salary,skills,job_type
0,Data Scientist-Artificial Intelligence,IBM,Mid-Senior level,"₹1,000,000.00\n -\n ₹3,0...","Python, SQL, Machine Learning, Artificial Inte...",Full-time
1,Senior Data Scientist - I,MetLife,Mid-Senior level,None,"Python, Machine Learning, NLP, TensorFlow, PyT...",Full-time
2,Senior Data Scientist,SourcingXPress,Mid-Senior level,"Base pay range ₹2,000,000.00/yr - ₹4,000,000.0...","Python, Machine Learning, Deep Learning, AWS, ...",Full-time
3,Sr Advanced Data Scientist,Honeywell Technologies,Mid-Senior level,None,"Python, R, Machine Learning, Azure, Databricks",Full-time
4,Senior Data Scientist I,MetLife,Mid-Senior level,None,"Python, Machine Learning, NLP, TensorFlow, PyT...",Full-time
5,Senior Data Scientist,Amplify Health,Mid-Senior level,"₹2,000,000.00\n -\n ₹4,0...","Python, SQL, Machine Learning, Deep Learning, ...",Full-time
6,Senior Data Scientist,SEI,Mid-Senior level,"₹4,000,000.00\n -\n ₹5,5...","Python, SQL, R, Machine Learning, Artificial I...",Full-time
7,Lead Data Scientist,AtkinsRéalis,Mid-Senior level,"₹1,000,000.00\n -\n ₹3,0...","Python, Machine Learning, Deep Learning, Tenso...",Full-time
8,Data Scientist - Machine Learning,United Airlines India Knowledge Center,Mid-Senior level,"₹1,200,000.00\n -\n ₹1,8...","Python, SQL, Machine Learning, Artificial Inte...",Full-time
9,Lead Data Scientist- Gen AI-ML- Vice president,Citi,Not Applicable,None,"Python, SQL, Machine Learning, NLP, TensorFlow...",Full-time
10,Sr Advanced Data Scientist,Honeywell Technologies,Mid-Senior level,"₹2,000,000.00\n -\n ₹4,0...","Python, R, Machine Learning, Azure, Databricks",Full-time
11,Data Scientist,Thales,Not Applicable,"₹1,200,000.00\n -\n ₹1,8...","Python, SQL, Machine Learning, Artificial Inte...",Full-time
12,AI/ML Data Science / Gen AI / MLOps,Cognizant,Mid-Senior level,"₹1,500,000.00\n -\n ₹2,5...","Python, Machine Learning, TensorFlow, PyTorch,...",Full-time
13,Machine Learning Engineer,Simplify Healthcare,Mid-Senior level,None,"Python, SQL, AWS, Azure, GCP, Spark, Databricks",Full-time
14,Senior Data Scientist,"InvoiceCloud, Inc.",Mid-Senior level,"₹4,000,000.00\n -\n ₹5,5...","Python, SQL, Machine Learning, Deep Learning, ...",Full-time
15,Principal Data Scientist,Atlassian,Mid-Senior level,None,"Python, SQL, R, Machine Learning, Pandas, NumP...",Full-time
16,Data Scientist I,Kroll,Entry level,"₹1,000,000.00\n -\n ₹3,0...","Python, Machine Learning, Deep Learning, NLP, ...",Full-time
17,Data Scientist + Databricks AI/ML - Sr Architect,Birlasoft,Mid-Senior level,None,"Python, SQL, NLP, TensorFlow, PyTorch, Scikit-...",Full-time
18,Senior Principal Data Scientist,AtkinsRéalis,Mid-Senior level,"₹5,000,000.00\n -\n ₹7,0...","Python, Machine Learning, NLP, TensorFlow, PyT...",Full-time
19,Data Science and AIML Lead - AITDS,Cognizant,Mid-Senior level,None,"Python, Machine Learning, TensorFlow, PyTorch,...",Full-time

In [220]:
import re

def extract_salary(salary):

    if pd.isna(salary):
        return pd.Series([None, None])

    numbers = re.findall(
        r"[\d,]+(?:\.\d+)?",
        str(salary)
    )

    numbers = [
        float(x.replace(",", ""))
        for x in numbers
    ]

    if len(numbers) >= 2:
        return pd.Series([numbers[0], numbers[1]])

    elif len(numbers) == 1:
        return pd.Series([numbers[0], numbers[0]])

    return pd.Series([None, None])

In [221]:
df[["salary_min", "salary_max"]] = df["salary"].apply(
    extract_salary
)

In [222]:
from collections import Counter

all_skills = []

for skills in df["skills"].dropna():
    for skill in skills.split(","):
        all_skills.append(skill.strip())

skill_counts = Counter(all_skills)

print(skill_counts.most_common(20))

[('Python', 519), ('Machine Learning', 459), ('Azure', 383), ('SQL', 321), ('AWS', 313), ('TensorFlow', 293), ('PyTorch', 293), ('GCP', 277), ('Scikit-learn', 250), ('NLP', 232), ('Deep Learning', 225), ('Databricks', 177), ('Pandas', 173), ('Docker', 156), ('Spark', 149), ('Git', 146), ('Artificial Intelligence', 140), ('Kubernetes', 117), ('NumPy', 109), ('Hugging Face', 92)]

In [223]:
skills_df = pd.DataFrame(
    skill_counts.items(),
    columns=["Skill", "Job_Count"]
)

skills_df = skills_df.sort_values(
    "Job_Count",
    ascending=False
)

skills_df.head(20)

                      Skill  Job_Count
0                    Python        519
2          Machine Learning        459
12                    Azure        383
1                       SQL        321
11                      AWS        313
6                   PyTorch        293
5                TensorFlow        293
13                      GCP        277
16             Scikit-learn        250
4                       NLP        232
17            Deep Learning        225
18               Databricks        177
9                    Pandas        173
20                   Docker        156
23                    Spark        149
24                      Git        146
3   Artificial Intelligence        140
14               Kubernetes        117
25                    NumPy        109
8              Hugging Face         92

In [224]:
df.to_csv(
    "linkedin_jobs_final.csv",
    index=False
)

print("CSV saved successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

CSV saved successfully!
Rows: 600
Columns: 12

In [225]:
import os

print(os.path.abspath("linkedin_jobs_final.csv"))

c:\Data Science\Project\Analysis\Job_Market_Salary_Analysis\notebooks\linkedin_jobs_final.csv

In [226]:
df.head()

,title,company,location,job_url,posted_text,posted_date,experience,salary,skills,job_type,salary_min,salary_max
0,Data Scientist-Artificial Intelligence,IBM,"Kochi, Kerala, India",https://in.linkedin.com/jobs/view/data-scienti...,18 hours ago,2026-08-25,Mid-Senior level,"₹1,000,000.00\n -\n ₹3,0...","Python, SQL, Machine Learning, Artificial Inte...",Full-time,1000000.0,3000000.0
1,Senior Data Scientist - I,MetLife,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/senior-data-...,22 hours ago,2026-08-25,Mid-Senior level,None,"Python, Machine Learning, NLP, TensorFlow, PyT...",Full-time,NaN,NaN
2,Senior Data Scientist,SourcingXPress,"Gurgaon, Haryana, India",https://in.linkedin.com/jobs/view/senior-data-...,5 months ago,2026-03-16,Mid-Senior level,"Base pay range ₹2,000,000.00/yr - ₹4,000,000.0...","Python, Machine Learning, Deep Learning, AWS, ...",Full-time,2000000.0,4000000.0
3,Sr Advanced Data Scientist,Honeywell Technologies,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/sr-advanced-...,1 week ago,2026-08-18,Mid-Senior level,None,"Python, R, Machine Learning, Azure, Databricks",Full-time,NaN,NaN
4,Senior Data Scientist I,MetLife,"Pune Division, Maharashtra, India",https://in.linkedin.com/jobs/view/senior-data-...,3 weeks ago,2026-08-03,Mid-Senior level,None,"Python, Machine Learning, NLP, TensorFlow, PyT...",Full-time,NaN,NaN